/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MBF;

import static MBF.MainPanel.errWin;
import fr.esrf.tangoatk.core.AttributePolledList;
import fr.esrf.tangoatk.core.ConnectionException;
import fr.esrf.tangoatk.core.attribute.EnumScalar;
import fr.esrf.tangoatk.core.attribute.NumberScalar;
import fr.esrf.tangoatk.widget.util.ATKGraphicsUtils;

/**
 *
 * @author pons
 */
public class TuneFitConfigPanel extends javax.swing.JFrame {
  
  private String devName;
  private AttributePolledList attList;
  
  private NumberScalar maxPeaksModel;
  private NumberScalar minHeightModel;
  private NumberScalar minWidthModel;
  private NumberScalar minSpacingModel;
  private NumberScalar windowStartModel;
  private NumberScalar smoothingModel;
  private EnumScalar dataModel;
  private NumberScalar maxWidthModel;
  private NumberScalar maxErrorModel;
  private NumberScalar windowLengthModel;


  /**
   * Creates new form TuneFitConfigPanel
   */
  public TuneFitConfigPanel(String devName) {

    initComponents();
    
    attList = new AttributePolledList();
    attList.addErrorListener(errWin);
    attList.setForceRefresh(false);
    attList.setSynchronizedPeriod(true);
    this.devName = devName;
    
    try {

      maxPeaksModel = (NumberScalar) attList.add(devName + "/CONFIG_MAX_PEAKS_S");
      maxPeaksEditor.setModel(maxPeaksModel);
      minHeightModel = (NumberScalar) attList.add(devName + "/CONFIG_MINIMUM_HEIGHT_S");
      minHeightEditor.setModel(minHeightModel);
      minWidthModel = (NumberScalar) attList.add(devName + "/CONFIG_MINIMUM_WIDTH_S");
      minWidthEditor.setModel(minWidthModel);
      minSpacingModel = (NumberScalar) attList.add(devName + "/CONFIG_MINIMUM_SPACING_S");
      minSpacingEditor.setModel(minSpacingModel);
      windowStartModel = (NumberScalar) attList.add(devName + "/CONFIG_WINDOW_START_S");
      windowStartEditor.setModel(windowStartModel);
      smoothingModel = (NumberScalar) attList.add(devName + "/CONFIG_SMOOTHING_S");
      smoothingEditor.setModel(smoothingModel);
      dataModel = (EnumScalar) attList.add(devName + "/CONFIG_WEIGHT_DATA_S");
      dataEditor.setEnumModel(dataModel);
      maxWidthModel = (NumberScalar) attList.add(devName + "/CONFIG_MAXIMUM_WIDTH_S");
      maxWidthEditor.setModel(maxWidthModel);
      maxErrorModel = (NumberScalar) attList.add(devName + "/CONFIG_MAXIMUM_FIT_ERROR_S");
      maxErrorEditor.setModel(maxErrorModel);
      windowLengthModel = (NumberScalar) attList.add(devName + "/CONFIG_WINDOW_LENGTH_S");
      windowLengthEditor.setModel(windowLengthModel);
      

    } catch (ConnectionException ex) {
    }

    attList.setRefreshInterval(1000);
    setTitle("Tune Fit Config [" + devName + "]");
    ATKGraphicsUtils.centerFrameOnScreen(this);
  }
  
  public void setVisible(boolean visible) {

    if (visible) {
      attList.startRefresher();
    } else {
      attList.stopRefresher();
    }

    super.setVisible(visible);

  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    java.awt.GridBagConstraints gridBagConstraints;

    configPanel = new javax.swing.JPanel();
    jLabel2 = new javax.swing.JLabel();
    maxPeaksEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel3 = new javax.swing.JLabel();
    minHeightEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel4 = new javax.swing.JLabel();
    minWidthEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel5 = new javax.swing.JLabel();
    minSpacingEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel6 = new javax.swing.JLabel();
    windowStartEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel7 = new javax.swing.JLabel();
    smoothingEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel8 = new javax.swing.JLabel();
    dataEditor = new fr.esrf.tangoatk.widget.attribute.EnumScalarComboEditor();
    jLabel9 = new javax.swing.JLabel();
    maxWidthEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel10 = new javax.swing.JLabel();
    maxErrorEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jLabel11 = new javax.swing.JLabel();
    windowLengthEditor = new fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor();
    jPanel1 = new javax.swing.JPanel();
    dismissButton = new javax.swing.JButton();

    configPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Config"));
    configPanel.setLayout(new java.awt.GridBagLayout());

    jLabel2.setText("Max Peaks");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    configPanel.add(jLabel2, gridBagConstraints);

    maxPeaksEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(maxPeaksEditor, gridBagConstraints);

    jLabel3.setText("Min Height");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    configPanel.add(jLabel3, gridBagConstraints);

    minHeightEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(minHeightEditor, gridBagConstraints);

    jLabel4.setText("Min Width");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    configPanel.add(jLabel4, gridBagConstraints);

    minWidthEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(minWidthEditor, gridBagConstraints);

    jLabel5.setText("Min Spacing");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    configPanel.add(jLabel5, gridBagConstraints);

    minSpacingEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(minSpacingEditor, gridBagConstraints);

    jLabel6.setText("Window start");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 0;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    configPanel.add(jLabel6, gridBagConstraints);

    windowStartEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 1;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(windowStartEditor, gridBagConstraints);

    jLabel7.setText("Smoothing");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    configPanel.add(jLabel7, gridBagConstraints);

    smoothingEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 0;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(smoothingEditor, gridBagConstraints);

    jLabel8.setText("Data");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    configPanel.add(jLabel8, gridBagConstraints);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 1;
    gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
    configPanel.add(dataEditor, gridBagConstraints);

    jLabel9.setText("Max width");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    configPanel.add(jLabel9, gridBagConstraints);

    maxWidthEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 2;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(maxWidthEditor, gridBagConstraints);

    jLabel10.setText("Max error");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    configPanel.add(jLabel10, gridBagConstraints);

    maxErrorEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 3;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(maxErrorEditor, gridBagConstraints);

    jLabel11.setText("Window length");
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 2;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
    gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 0);
    configPanel.add(jLabel11, gridBagConstraints);

    windowLengthEditor.setOpaque(false);
    gridBagConstraints = new java.awt.GridBagConstraints();
    gridBagConstraints.gridx = 3;
    gridBagConstraints.gridy = 4;
    gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
    configPanel.add(windowLengthEditor, gridBagConstraints);

    getContentPane().add(configPanel, java.awt.BorderLayout.CENTER);

    jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

    dismissButton.setText("Dismiss");
    dismissButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        dismissButtonActionPerformed(evt);
      }
    });
    jPanel1.add(dismissButton);

    getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void dismissButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dismissButtonActionPerformed
    // TODO add your handling code here:
    setVisible(false);
  }//GEN-LAST:event_dismissButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel configPanel;
  private fr.esrf.tangoatk.widget.attribute.EnumScalarComboEditor dataEditor;
  private javax.swing.JButton dismissButton;
  private javax.swing.JLabel jLabel10;
  private javax.swing.JLabel jLabel11;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor maxErrorEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor maxPeaksEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor maxWidthEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor minHeightEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor minSpacingEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor minWidthEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor smoothingEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor windowLengthEditor;
  private fr.esrf.tangoatk.widget.attribute.NumberScalarWheelEditor windowStartEditor;
  // End of variables declaration//GEN-END:variables
}
