#!/bin/bash

# Takes 4 parameters
#  - path to a .config file
#  - path of MBF_HOME
#  - path of the MACRO_DIR where Python macros for MacroServer are stored
#  - path of top directory of MBF-Tango

CONFIG_FILE=$1
MBF_HOME=$2
MACRO_DIR=$3
TOP=$4

# Reads key from given config file.  Called thus:
#
#   read_key file key
read_key()
{
    sed -n "/^$2 *= */{s///; p; q;}" "$1"
}

IOC_NAME="$(basename $CONFIG_FILE ".config")"
IOC_DIR="$MBF_HOME/iocs"

VAR_SUBST=""
VAR_SUBST="$VAR_SUBST;s:@@DEVICE_NAME@@:$(read_key $CONFIG_FILE tango_device_name):"
VAR_SUBST="$VAR_SUBST;s:@@INSTANCE@@:$(read_key $CONFIG_FILE tango_instance):"
VAR_SUBST="$VAR_SUBST;s:@@COMMAND@@:$IOC_DIR/$IOC_NAME:"
VAR_SUBST="$VAR_SUBST;s:@@TMUX_SESSION_NAME@@:$(read_key $CONFIG_FILE tango_tmux_session_name):"
sed "$VAR_SUBST" MBFStartIOC_template.res
