/*----- PROTECTED REGION ID(MBFCleaningClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        MBFCleaningClass.h
//
// description : Include for the MBFCleaning root class.
//               This class is the singleton class for
//                the MBFCleaning device class.
//               It contains all properties and methods which the 
//               MBFCleaning requires only once e.g. the commands.
//
// project :     MBFCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2018
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef MBFCleaningClass_H
#define MBFCleaningClass_H

#include <tango.h>
#include <MBFCleaning.h>


/*----- PROTECTED REGION END -----*/	//	MBFCleaningClass.h


namespace MBFCleaning_ns
{
/*----- PROTECTED REGION ID(MBFCleaningClass::classes for dynamic creation) ENABLED START -----*/

class ScraperAttribute: public Tango::Attr {

public:

    int scrIdx;

    //-----------------------------------------------------------------------------
    // Constructor

    ScraperAttribute(const char *attName,int scrIdx)
            :Attr(attName,Tango::DEV_DOUBLE,Tango::READ_WRITE) {
      this->scrIdx = scrIdx;
    };

    ~ScraperAttribute() {};

    //-----------------------------------------------------------------------------
    // Write/Read mehod

    virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att) {
      (static_cast<MBFCleaning *>(dev))->read_scraper_attribute(att,this);
    }
    virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att) {
      (static_cast<MBFCleaning *>(dev))->write_scraper_attribute(att,this);
    }

};


/*----- PROTECTED REGION END -----*/	//	MBFCleaningClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute FreqMin class definition
class FreqMinAttrib: public Tango::Attr
{
public:
	FreqMinAttrib():Attr("FreqMin",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {}
	~FreqMinAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_FreqMin(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_FreqMin(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_FreqMin_allowed(ty);}
};

//	Attribute FreqMax class definition
class FreqMaxAttrib: public Tango::Attr
{
public:
	FreqMaxAttrib():Attr("FreqMax",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {}
	~FreqMaxAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_FreqMax(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_FreqMax(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_FreqMax_allowed(ty);}
};

//	Attribute SweepPeriod class definition
class SweepPeriodAttrib: public Tango::Attr
{
public:
	SweepPeriodAttrib():Attr("SweepPeriod",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {}
	~SweepPeriodAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_SweepPeriod(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_SweepPeriod(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_SweepPeriod_allowed(ty);}
};

//	Attribute CleaningTime class definition
class CleaningTimeAttrib: public Tango::Attr
{
public:
	CleaningTimeAttrib():Attr("CleaningTime",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {}
	~CleaningTimeAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_CleaningTime(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_CleaningTime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_CleaningTime_allowed(ty);}
};

//	Attribute Gain class definition
class GainAttrib: public Tango::Attr
{
public:
	GainAttrib():Attr("Gain",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {}
	~GainAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_Gain(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_Gain(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_Gain_allowed(ty);}
};

//	Attribute ConfigFileName class definition
class ConfigFileNameAttrib: public Tango::Attr
{
public:
	ConfigFileNameAttrib():Attr("ConfigFileName",
			Tango::DEV_STRING, Tango::READ) {}
	~ConfigFileNameAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_ConfigFileName(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_ConfigFileName_allowed(ty);}
};

//	Attribute ExternalSweep class definition
class ExternalSweepAttrib: public Tango::Attr
{
public:
	ExternalSweepAttrib():Attr("ExternalSweep",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {}
	~ExternalSweepAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_ExternalSweep(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<MBFCleaning *>(dev))->write_ExternalSweep(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_ExternalSweep_allowed(ty);}
};

//	Attribute SweepState class definition
class SweepStateAttrib: public Tango::Attr
{
public:
	SweepStateAttrib():Attr("SweepState",
			Tango::DEV_STATE, Tango::READ) {}
	~SweepStateAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_SweepState(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_SweepState_allowed(ty);}
};

//	Attribute UsedScrapers class definition
class UsedScrapersAttrib: public Tango::SpectrumAttr
{
public:
	// Constants for UsedScrapers attribute
	constexpr static long X_DATA_SIZE = 16;
	UsedScrapersAttrib():SpectrumAttr("UsedScrapers",
			Tango::DEV_BOOLEAN, Tango::READ, UsedScrapersAttrib::X_DATA_SIZE) {}
	~UsedScrapersAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<MBFCleaning *>(dev))->read_UsedScrapers(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<MBFCleaning *>(dev))->is_UsedScrapers_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command StartCleaning class definition
class StartCleaningClass : public Tango::Command
{
public:
	StartCleaningClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	StartCleaningClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~StartCleaningClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_StartCleaning_allowed(any);}
};

//	Command LoadConfigurationFile class definition
class LoadConfigurationFileClass : public Tango::Command
{
public:
	LoadConfigurationFileClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	LoadConfigurationFileClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~LoadConfigurationFileClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_LoadConfigurationFile_allowed(any);}
};

//	Command SaveConfigurationFile class definition
class SaveConfigurationFileClass : public Tango::Command
{
public:
	SaveConfigurationFileClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	SaveConfigurationFileClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~SaveConfigurationFileClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_SaveConfigurationFile_allowed(any);}
};

//	Command GetConfigurationFilePath class definition
class GetConfigurationFilePathClass : public Tango::Command
{
public:
	GetConfigurationFilePathClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	GetConfigurationFilePathClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~GetConfigurationFilePathClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_GetConfigurationFilePath_allowed(any);}
};

//	Command Sweep class definition
class SweepClass : public Tango::Command
{
public:
	SweepClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	SweepClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~SweepClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_Sweep_allowed(any);}
};

//	Command EndCleaning class definition
class EndCleaningClass : public Tango::Command
{
public:
	EndCleaningClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	EndCleaningClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~EndCleaningClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_EndCleaning_allowed(any);}
};

//	Command DoAll class definition
class DoAllClass : public Tango::Command
{
public:
	DoAllClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	DoAllClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~DoAllClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_DoAll_allowed(any);}
};

//	Command Stop class definition
class StopClass : public Tango::Command
{
public:
	StopClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	StopClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~StopClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_Stop_allowed(any);}
};

//	Command SelectScraper class definition
class SelectScraperClass : public Tango::Command
{
public:
	SelectScraperClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	SelectScraperClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~SelectScraperClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_SelectScraper_allowed(any);}
};

//	Command StartPermanent class definition
class StartPermanentClass : public Tango::Command
{
public:
	StartPermanentClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	StartPermanentClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~StartPermanentClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_StartPermanent_allowed(any);}
};

//	Command StopPermanent class definition
class StopPermanentClass : public Tango::Command
{
public:
	StopPermanentClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	StopPermanentClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~StopPermanentClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<MBFCleaning *>(dev))->is_StopPermanent_allowed(any);}
};


/**
 *	The MBFCleaningClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  MBFCleaningClass : public Tango::DeviceClass
#else
class MBFCleaningClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(MBFCleaningClass::Additional DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	MBFCleaningClass::Additional DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
		//	Method prototypes
		static MBFCleaningClass *init(const char *);
		static MBFCleaningClass *instance();
		~MBFCleaningClass();
		Tango::DbDatum	get_class_property(std::string &);
		Tango::DbDatum	get_default_device_property(std::string &);
		Tango::DbDatum	get_default_class_property(std::string &);

	protected:
		MBFCleaningClass(std::string &);
		static MBFCleaningClass *_instance;
		void command_factory();
		void attribute_factory(std::vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		std::string get_cvstag();
		std::string get_cvsroot();

	private:
		void device_factory(TANGO_UNUSED(const Tango::DevVarStringArray *));
		void create_static_attribute_list(std::vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,std::vector<Tango::Attr *> &);
		std::vector<std::string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname);
};

}	//	End of namespace

#endif   //	MBFCleaning_H
