/*----- PROTECTED REGION ID(SYMBFCleaningClass.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        SYMBFCleaningClass.cpp
//
// description : C++ source for the SYMBFCleaningClass.
//               A singleton class derived from DeviceClass.
//               It implements the command and attribute list
//               and all properties and methods required
//               by the SYMBFCleaning once per process.
//
// project :     SyCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SYMBFCleaningClass.h>

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass.cpp

//-------------------------------------------------------------------
/**
 *	Create SYMBFCleaningClass singleton and
 *	return it in a C function for Python usage
 */
//-------------------------------------------------------------------
extern "C" {
#ifdef _TG_WINDOWS_

__declspec(dllexport)

#endif

	Tango::DeviceClass *_create_SYMBFCleaning_class(const char *name) {
		return SYMBFCleaning_ns::SYMBFCleaningClass::init(name);
	}
}

namespace SYMBFCleaning_ns
{
//===================================================================
//	Initialize pointer for singleton pattern
//===================================================================
SYMBFCleaningClass *SYMBFCleaningClass::_instance = NULL;

//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::SYMBFCleaningClass(string &s)
 * description : 	constructor for the SYMBFCleaningClass
 *
 * @param s	The class name
 */
//--------------------------------------------------------
SYMBFCleaningClass::SYMBFCleaningClass(string &s):Tango::DeviceClass(s)
{
	cout2 << "Entering SYMBFCleaningClass constructor" << endl;
	set_default_property();
	write_class_property();

	/*----- PROTECTED REGION ID(SYMBFCleaningClass::constructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::constructor

	cout2 << "Leaving SYMBFCleaningClass constructor" << endl;
}

//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::~SYMBFCleaningClass()
 * description : 	destructor for the SYMBFCleaningClass
 */
//--------------------------------------------------------
SYMBFCleaningClass::~SYMBFCleaningClass()
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::destructor) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::destructor

	_instance = NULL;
}


//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::init
 * description : 	Create the object if not already done.
 *                  Otherwise, just return a pointer to the object
 *
 * @param	name	The class name
 */
//--------------------------------------------------------
SYMBFCleaningClass *SYMBFCleaningClass::init(const char *name)
{
	if (_instance == NULL)
	{
		try
		{
			string s(name);
			_instance = new SYMBFCleaningClass(s);
		}
		catch (bad_alloc &)
		{
			throw;
		}
	}
	return _instance;
}

//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::instance
 * description : 	Check if object already created,
 *                  and return a pointer to the object
 */
//--------------------------------------------------------
SYMBFCleaningClass *SYMBFCleaningClass::instance()
{
	if (_instance == NULL)
	{
		cerr << "Class is not initialised !!" << endl;
		exit(-1);
	}
	return _instance;
}



//===================================================================
//	Command execution method calls
//===================================================================
//--------------------------------------------------------
/**
 * method : 		GetConfigurationFilePathClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *GetConfigurationFilePathClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "GetConfigurationFilePathClass::execute(): arrived" << endl;
	return insert((static_cast<SYMBFCleaning *>(device))->get_configuration_file_path());
}

//--------------------------------------------------------
/**
 * method : 		LoadConfigurationFileClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *LoadConfigurationFileClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "LoadConfigurationFileClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<SYMBFCleaning *>(device))->load_configuration_file(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SaveConfigurationFileClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SaveConfigurationFileClass::execute(Tango::DeviceImpl *device, const CORBA::Any &in_any)
{
	cout2 << "SaveConfigurationFileClass::execute(): arrived" << endl;
	Tango::DevString argin;
	extract(in_any, argin);
	((static_cast<SYMBFCleaning *>(device))->save_configuration_file(argin));
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SweepOnClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SweepOnClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SweepOnClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->sweep_on());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		SweepOffClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *SweepOffClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "SweepOffClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->sweep_off());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		EndCleaningClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *EndCleaningClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "EndCleaningClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->end_cleaning());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StopClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StopClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StopClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->stop());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		StartCleaningClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *StartCleaningClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "StartCleaningClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->start_cleaning());
	return new CORBA::Any();
}

//--------------------------------------------------------
/**
 * method : 		ResetClass::execute()
 * description : 	method to trigger the execution of the command.
 *
 * @param	device	The device on which the command must be executed
 * @param	in_any	The command input data
 *
 *	returns The command output data (packed in the Any object)
 */
//--------------------------------------------------------
CORBA::Any *ResetClass::execute(Tango::DeviceImpl *device, TANGO_UNUSED(const CORBA::Any &in_any))
{
	cout2 << "ResetClass::execute(): arrived" << endl;
	((static_cast<SYMBFCleaning *>(device))->reset());
	return new CORBA::Any();
}


//===================================================================
//	Properties management
//===================================================================
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::get_class_property()
 *	Description : Get the class property for specified name.
 */
//--------------------------------------------------------
Tango::DbDatum SYMBFCleaningClass::get_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_prop.size() ; i++)
		if (cl_prop[i].name == prop_name)
			return cl_prop[i];
	//	if not found, returns  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::get_default_device_property()
 *	Description : Return the default value for device property.
 */
//--------------------------------------------------------
Tango::DbDatum SYMBFCleaningClass::get_default_device_property(string &prop_name)
{
	for (unsigned int i=0 ; i<dev_def_prop.size() ; i++)
		if (dev_def_prop[i].name == prop_name)
			return dev_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::get_default_class_property()
 *	Description : Return the default value for class property.
 */
//--------------------------------------------------------
Tango::DbDatum SYMBFCleaningClass::get_default_class_property(string &prop_name)
{
	for (unsigned int i=0 ; i<cl_def_prop.size() ; i++)
		if (cl_def_prop[i].name == prop_name)
			return cl_def_prop[i];
	//	if not found, return  an empty DbDatum
	return Tango::DbDatum(prop_name);
}


//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::set_default_property()
 *	Description : Set default property (class and device) for wizard.
 *                For each property, add to wizard property name and description.
 *                If default value has been set, add it to wizard property and
 *                store it in a DbDatum.
 */
//--------------------------------------------------------
void SYMBFCleaningClass::set_default_property()
{
	string	prop_name;
	string	prop_desc;
	string	prop_def;
	vector<string>	vect_data;

	//	Set Default Class Properties

	//	Set Default device Properties
	prop_name = "EpicsName";
	prop_desc = "Name of the MBF Epics device";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "MBFName";
	prop_desc = "Name of MBFControl device";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "VPhaseAttName";
	prop_desc = "Name of the VPahe attribue";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "InjectionDelayAttName";
	prop_desc = "Name of the Injection Delay attribute";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "UppScrapperName";
	prop_desc = "Name of the Upp scrapper device name";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "LowScrapperName";
	prop_desc = "Name of the low scrapper device name";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Ampli1Name";
	prop_desc = "Name of the Ampli1 device";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "Ampli2Name";
	prop_desc = "Name of the Ampli2 device";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "SettingsFilesPath";
	prop_desc = "Path were are stored settings file";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
	prop_name = "LastLoaded";
	prop_desc = "Last loaded file";
	prop_def  = "";
	vect_data.clear();
	if (prop_def.length()>0)
	{
		Tango::DbDatum	data(prop_name);
		data << vect_data ;
		dev_def_prop.push_back(data);
		add_wiz_dev_prop(prop_name, prop_desc,  prop_def);
	}
	else
		add_wiz_dev_prop(prop_name, prop_desc);
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::write_class_property()
 *	Description : Set class description fields as property in database
 */
//--------------------------------------------------------
void SYMBFCleaningClass::write_class_property()
{
	//	First time, check if database used
	if (Tango::Util::_UseDb == false)
		return;

	Tango::DbData	data;
	string	classname = get_name();
	string	header;
	string::size_type	start, end;

	//	Put title
	Tango::DbDatum	title("ProjectTitle");
	string	str_title("SyCleaning");
	title << str_title;
	data.push_back(title);

	//	Put Description
	Tango::DbDatum	description("Description");
	vector<string>	str_desc;
	str_desc.push_back("A class to handle resonant cleaning in the booster");
	description << str_desc;
	data.push_back(description);

	//  Put inheritance
	Tango::DbDatum	inher_datum("InheritedFrom");
	vector<string> inheritance;
	inheritance.push_back("TANGO_BASE_CLASS");
	inher_datum << inheritance;
	data.push_back(inher_datum);

	//	Call database and and values
	get_db_class()->put_property(data);
}

//===================================================================
//	Factory methods
//===================================================================

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::device_factory()
 *	Description : Create the device object(s)
 *                and store them in the device list
 */
//--------------------------------------------------------
void SYMBFCleaningClass::device_factory(const Tango::DevVarStringArray *devlist_ptr)
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::device_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::device_factory_before

	//	Create devices and add it into the device list
	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		cout4 << "Device name : " << (*devlist_ptr)[i].in() << endl;
		device_list.push_back(new SYMBFCleaning(this, (*devlist_ptr)[i]));
	}

	//	Manage dynamic attributes if any
	erase_dynamic_attributes(devlist_ptr, get_class_attr()->get_attr_list());

	//	Export devices to the outside world
	for (unsigned long i=1 ; i<=devlist_ptr->length() ; i++)
	{
		//	Add dynamic attributes if any
		SYMBFCleaning *dev = static_cast<SYMBFCleaning *>(device_list[device_list.size()-i]);
		dev->add_dynamic_attributes();

		//	Check before if database used.
		if ((Tango::Util::_UseDb == true) && (Tango::Util::_FileDb == false))
			export_device(dev);
		else
			export_device(dev, dev->get_name().c_str());
	}

	/*----- PROTECTED REGION ID(SYMBFCleaningClass::device_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::device_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::attribute_factory()
 *	Description : Create the attribute object(s)
 *                and store them in the attribute list
 */
//--------------------------------------------------------
void SYMBFCleaningClass::attribute_factory(vector<Tango::Attr *> &att_list)
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::attribute_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::attribute_factory_before
	//	Attribute : ConfigFileName
	ConfigFileNameAttrib	*configfilename = new ConfigFileNameAttrib();
	Tango::UserDefaultAttrProp	configfilename_prop;
	//	description	not set for ConfigFileName
	//	label	not set for ConfigFileName
	//	unit	not set for ConfigFileName
	//	standard_unit	not set for ConfigFileName
	//	display_unit	not set for ConfigFileName
	//	format	not set for ConfigFileName
	//	max_value	not set for ConfigFileName
	//	min_value	not set for ConfigFileName
	//	max_alarm	not set for ConfigFileName
	//	min_alarm	not set for ConfigFileName
	//	max_warning	not set for ConfigFileName
	//	min_warning	not set for ConfigFileName
	//	delta_t	not set for ConfigFileName
	//	delta_val	not set for ConfigFileName
	
	configfilename->set_default_properties(configfilename_prop);
	//	Not Polled
	configfilename->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(configfilename);

	//	Attribute : Phase
	PhaseAttrib	*phase = new PhaseAttrib();
	Tango::UserDefaultAttrProp	phase_prop;
	//	description	not set for Phase
	//	label	not set for Phase
	phase_prop.set_unit("Volt");
	//	standard_unit	not set for Phase
	//	display_unit	not set for Phase
	phase_prop.set_format("%6.3f");
	//	max_value	not set for Phase
	//	min_value	not set for Phase
	//	max_alarm	not set for Phase
	//	min_alarm	not set for Phase
	//	max_warning	not set for Phase
	//	min_warning	not set for Phase
	//	delta_t	not set for Phase
	//	delta_val	not set for Phase
	
	phase->set_default_properties(phase_prop);
	//	Not Polled
	phase->set_disp_level(Tango::OPERATOR);
	phase->set_memorized();
	phase->set_memorized_init(true);
	att_list.push_back(phase);

	//	Attribute : InjectionDelay
	InjectionDelayAttrib	*injectiondelay = new InjectionDelayAttrib();
	Tango::UserDefaultAttrProp	injectiondelay_prop;
	//	description	not set for InjectionDelay
	//	label	not set for InjectionDelay
	injectiondelay_prop.set_unit("ms");
	//	standard_unit	not set for InjectionDelay
	//	display_unit	not set for InjectionDelay
	injectiondelay_prop.set_format("%5.3f");
	injectiondelay_prop.set_max_value("95");
	injectiondelay_prop.set_min_value("0");
	//	max_alarm	not set for InjectionDelay
	//	min_alarm	not set for InjectionDelay
	//	max_warning	not set for InjectionDelay
	//	min_warning	not set for InjectionDelay
	//	delta_t	not set for InjectionDelay
	//	delta_val	not set for InjectionDelay
	
	injectiondelay->set_default_properties(injectiondelay_prop);
	//	Not Polled
	injectiondelay->set_disp_level(Tango::OPERATOR);
	injectiondelay->set_memorized();
	injectiondelay->set_memorized_init(true);
	att_list.push_back(injectiondelay);

	//	Attribute : CleaningTime
	CleaningTimeAttrib	*cleaningtime = new CleaningTimeAttrib();
	Tango::UserDefaultAttrProp	cleaningtime_prop;
	//	description	not set for CleaningTime
	//	label	not set for CleaningTime
	cleaningtime_prop.set_unit("ms");
	//	standard_unit	not set for CleaningTime
	//	display_unit	not set for CleaningTime
	cleaningtime_prop.set_format("%6.3f");
	//	max_value	not set for CleaningTime
	//	min_value	not set for CleaningTime
	//	max_alarm	not set for CleaningTime
	//	min_alarm	not set for CleaningTime
	//	max_warning	not set for CleaningTime
	//	min_warning	not set for CleaningTime
	//	delta_t	not set for CleaningTime
	//	delta_val	not set for CleaningTime
	
	cleaningtime->set_default_properties(cleaningtime_prop);
	//	Not Polled
	cleaningtime->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(cleaningtime);

	//	Attribute : Count
	CountAttrib	*count = new CountAttrib();
	Tango::UserDefaultAttrProp	count_prop;
	//	description	not set for Count
	//	label	not set for Count
	//	unit	not set for Count
	//	standard_unit	not set for Count
	//	display_unit	not set for Count
	//	format	not set for Count
	//	max_value	not set for Count
	//	min_value	not set for Count
	//	max_alarm	not set for Count
	//	min_alarm	not set for Count
	//	max_warning	not set for Count
	//	min_warning	not set for Count
	//	delta_t	not set for Count
	//	delta_val	not set for Count
	
	count->set_default_properties(count_prop);
	//	Not Polled
	count->set_disp_level(Tango::OPERATOR);
	count->set_memorized();
	count->set_memorized_init(true);
	att_list.push_back(count);

	//	Attribute : Dwell
	DwellAttrib	*dwell = new DwellAttrib();
	Tango::UserDefaultAttrProp	dwell_prop;
	//	description	not set for Dwell
	//	label	not set for Dwell
	//	unit	not set for Dwell
	//	standard_unit	not set for Dwell
	//	display_unit	not set for Dwell
	//	format	not set for Dwell
	//	max_value	not set for Dwell
	//	min_value	not set for Dwell
	//	max_alarm	not set for Dwell
	//	min_alarm	not set for Dwell
	//	max_warning	not set for Dwell
	//	min_warning	not set for Dwell
	//	delta_t	not set for Dwell
	//	delta_val	not set for Dwell
	
	dwell->set_default_properties(dwell_prop);
	//	Not Polled
	dwell->set_disp_level(Tango::OPERATOR);
	dwell->set_memorized();
	dwell->set_memorized_init(true);
	att_list.push_back(dwell);

	//	Attribute : Amplitude
	AmplitudeAttrib	*amplitude = new AmplitudeAttrib();
	Tango::UserDefaultAttrProp	amplitude_prop;
	//	description	not set for Amplitude
	//	label	not set for Amplitude
	//	unit	not set for Amplitude
	//	standard_unit	not set for Amplitude
	//	display_unit	not set for Amplitude
	amplitude_prop.set_format("%3d");
	amplitude_prop.set_max_value("127");
	amplitude_prop.set_min_value("0");
	//	max_alarm	not set for Amplitude
	//	min_alarm	not set for Amplitude
	//	max_warning	not set for Amplitude
	//	min_warning	not set for Amplitude
	//	delta_t	not set for Amplitude
	//	delta_val	not set for Amplitude
	
	amplitude->set_default_properties(amplitude_prop);
	//	Not Polled
	amplitude->set_disp_level(Tango::OPERATOR);
	amplitude->set_memorized();
	amplitude->set_memorized_init(true);
	att_list.push_back(amplitude);

	//	Attribute : UppScrapperPos
	UppScrapperPosAttrib	*uppscrapperpos = new UppScrapperPosAttrib();
	Tango::UserDefaultAttrProp	uppscrapperpos_prop;
	//	description	not set for UppScrapperPos
	//	label	not set for UppScrapperPos
	uppscrapperpos_prop.set_unit("mm");
	//	standard_unit	not set for UppScrapperPos
	//	display_unit	not set for UppScrapperPos
	uppscrapperpos_prop.set_format("%5.3f");
	//	max_value	not set for UppScrapperPos
	//	min_value	not set for UppScrapperPos
	//	max_alarm	not set for UppScrapperPos
	//	min_alarm	not set for UppScrapperPos
	//	max_warning	not set for UppScrapperPos
	//	min_warning	not set for UppScrapperPos
	//	delta_t	not set for UppScrapperPos
	//	delta_val	not set for UppScrapperPos
	
	uppscrapperpos->set_default_properties(uppscrapperpos_prop);
	//	Not Polled
	uppscrapperpos->set_disp_level(Tango::OPERATOR);
	uppscrapperpos->set_memorized();
	uppscrapperpos->set_memorized_init(true);
	att_list.push_back(uppscrapperpos);

	//	Attribute : LowScrapperPos
	LowScrapperPosAttrib	*lowscrapperpos = new LowScrapperPosAttrib();
	Tango::UserDefaultAttrProp	lowscrapperpos_prop;
	//	description	not set for LowScrapperPos
	//	label	not set for LowScrapperPos
	lowscrapperpos_prop.set_unit("mm");
	//	standard_unit	not set for LowScrapperPos
	//	display_unit	not set for LowScrapperPos
	lowscrapperpos_prop.set_format("%5.3f");
	//	max_value	not set for LowScrapperPos
	//	min_value	not set for LowScrapperPos
	//	max_alarm	not set for LowScrapperPos
	//	min_alarm	not set for LowScrapperPos
	//	max_warning	not set for LowScrapperPos
	//	min_warning	not set for LowScrapperPos
	//	delta_t	not set for LowScrapperPos
	//	delta_val	not set for LowScrapperPos
	
	lowscrapperpos->set_default_properties(lowscrapperpos_prop);
	//	Not Polled
	lowscrapperpos->set_disp_level(Tango::OPERATOR);
	lowscrapperpos->set_memorized();
	lowscrapperpos->set_memorized_init(true);
	att_list.push_back(lowscrapperpos);

	//	Attribute : PatternDelay
	PatternDelayAttrib	*patterndelay = new PatternDelayAttrib();
	Tango::UserDefaultAttrProp	patterndelay_prop;
	//	description	not set for PatternDelay
	//	label	not set for PatternDelay
	patterndelay_prop.set_unit("bunch");
	//	standard_unit	not set for PatternDelay
	//	display_unit	not set for PatternDelay
	patterndelay_prop.set_format("%3d");
	//	max_value	not set for PatternDelay
	//	min_value	not set for PatternDelay
	//	max_alarm	not set for PatternDelay
	//	min_alarm	not set for PatternDelay
	//	max_warning	not set for PatternDelay
	//	min_warning	not set for PatternDelay
	//	delta_t	not set for PatternDelay
	//	delta_val	not set for PatternDelay
	
	patterndelay->set_default_properties(patterndelay_prop);
	//	Not Polled
	patterndelay->set_disp_level(Tango::OPERATOR);
	patterndelay->set_memorized();
	patterndelay->set_memorized_init(true);
	att_list.push_back(patterndelay);

	//	Attribute : SwitchOFFAmplifier
	SwitchOFFAmplifierAttrib	*switchoffamplifier = new SwitchOFFAmplifierAttrib();
	Tango::UserDefaultAttrProp	switchoffamplifier_prop;
	//	description	not set for SwitchOFFAmplifier
	//	label	not set for SwitchOFFAmplifier
	//	unit	not set for SwitchOFFAmplifier
	//	standard_unit	not set for SwitchOFFAmplifier
	//	display_unit	not set for SwitchOFFAmplifier
	//	format	not set for SwitchOFFAmplifier
	//	max_value	not set for SwitchOFFAmplifier
	//	min_value	not set for SwitchOFFAmplifier
	//	max_alarm	not set for SwitchOFFAmplifier
	//	min_alarm	not set for SwitchOFFAmplifier
	//	max_warning	not set for SwitchOFFAmplifier
	//	min_warning	not set for SwitchOFFAmplifier
	//	delta_t	not set for SwitchOFFAmplifier
	//	delta_val	not set for SwitchOFFAmplifier
	
	switchoffamplifier->set_default_properties(switchoffamplifier_prop);
	//	Not Polled
	switchoffamplifier->set_disp_level(Tango::OPERATOR);
	switchoffamplifier->set_memorized();
	switchoffamplifier->set_memorized_init(true);
	att_list.push_back(switchoffamplifier);

	//	Attribute : CleaningPattern
	CleaningPatternAttrib	*cleaningpattern = new CleaningPatternAttrib();
	Tango::UserDefaultAttrProp	cleaningpattern_prop;
	//	description	not set for CleaningPattern
	//	label	not set for CleaningPattern
	//	unit	not set for CleaningPattern
	//	standard_unit	not set for CleaningPattern
	//	display_unit	not set for CleaningPattern
	cleaningpattern_prop.set_format("%d");
	cleaningpattern_prop.set_max_value("1");
	cleaningpattern_prop.set_min_value("-1");
	//	max_alarm	not set for CleaningPattern
	//	min_alarm	not set for CleaningPattern
	//	max_warning	not set for CleaningPattern
	//	min_warning	not set for CleaningPattern
	//	delta_t	not set for CleaningPattern
	//	delta_val	not set for CleaningPattern
	
	cleaningpattern->set_default_properties(cleaningpattern_prop);
	//	Not Polled
	cleaningpattern->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	att_list.push_back(cleaningpattern);

	
	//	Forwarded attribute Mode
	ModeAttrib *mode = new ModeAttrib("Mode");
	Tango::UserDefaultFwdAttrProp  mode_prop;
	mode_prop.set_label("Mode");
	mode->set_default_properties(mode_prop);
	att_list.push_back(mode);
	
	//	Forwarded attribute Harmonic
	HarmonicAttrib *harmonic = new HarmonicAttrib("Harmonic");
	Tango::UserDefaultFwdAttrProp  harmonic_prop;
	harmonic_prop.set_label("Harmonic");
	harmonic->set_default_properties(harmonic_prop);
	att_list.push_back(harmonic);
	
	//	Forwarded attribute CentralFreq
	CentralFreqAttrib *centralfreq = new CentralFreqAttrib("CentralFreq");
	Tango::UserDefaultFwdAttrProp  centralfreq_prop;
	centralfreq_prop.set_label("CentralFreq");
	centralfreq->set_default_properties(centralfreq_prop);
	att_list.push_back(centralfreq);
	
	//	Forwarded attribute DeltaFreq
	DeltaFreqAttrib *deltafreq = new DeltaFreqAttrib("DeltaFreq");
	Tango::UserDefaultFwdAttrProp  deltafreq_prop;
	deltafreq_prop.set_label("DeltaFreq");
	deltafreq->set_default_properties(deltafreq_prop);
	att_list.push_back(deltafreq);

	//	Create a list of static attributes
	create_static_attribute_list(get_class_attr()->get_attr_list());
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::attribute_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::attribute_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::pipe_factory()
 *	Description : Create the pipe object(s)
 *                and store them in the pipe list
 */
//--------------------------------------------------------
void SYMBFCleaningClass::pipe_factory()
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::pipe_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::pipe_factory_before
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::pipe_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::pipe_factory_after
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::command_factory()
 *	Description : Create the command object(s)
 *                and store them in the command list
 */
//--------------------------------------------------------
void SYMBFCleaningClass::command_factory()
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::command_factory_before) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::command_factory_before

	//	Set polling perod for command State
	Tango::Command	&stateCmd = get_cmd_by_name("State");
	stateCmd.set_polling_period(1000);
	

	//	Command GetConfigurationFilePath
	GetConfigurationFilePathClass	*pGetConfigurationFilePathCmd =
		new GetConfigurationFilePathClass("GetConfigurationFilePath",
			Tango::DEV_VOID, Tango::DEV_STRING,
			"",
			"Configuration file path",
			Tango::OPERATOR);
	command_list.push_back(pGetConfigurationFilePathCmd);

	//	Command LoadConfigurationFile
	LoadConfigurationFileClass	*pLoadConfigurationFileCmd =
		new LoadConfigurationFileClass("LoadConfigurationFile",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"Configuration file name (without the path)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pLoadConfigurationFileCmd);

	//	Command SaveConfigurationFile
	SaveConfigurationFileClass	*pSaveConfigurationFileCmd =
		new SaveConfigurationFileClass("SaveConfigurationFile",
			Tango::DEV_STRING, Tango::DEV_VOID,
			"Configuration file name (without the path)",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSaveConfigurationFileCmd);

	//	Command SweepOn
	SweepOnClass	*pSweepOnCmd =
		new SweepOnClass("SweepOn",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSweepOnCmd);

	//	Command SweepOff
	SweepOffClass	*pSweepOffCmd =
		new SweepOffClass("SweepOff",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pSweepOffCmd);

	//	Command EndCleaning
	EndCleaningClass	*pEndCleaningCmd =
		new EndCleaningClass("EndCleaning",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pEndCleaningCmd);

	//	Command Stop
	StopClass	*pStopCmd =
		new StopClass("Stop",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStopCmd);

	//	Command StartCleaning
	StartCleaningClass	*pStartCleaningCmd =
		new StartCleaningClass("StartCleaning",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pStartCleaningCmd);

	//	Command Reset
	ResetClass	*pResetCmd =
		new ResetClass("Reset",
			Tango::DEV_VOID, Tango::DEV_VOID,
			"",
			"",
			Tango::OPERATOR);
	command_list.push_back(pResetCmd);

	/*----- PROTECTED REGION ID(SYMBFCleaningClass::command_factory_after) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::command_factory_after
}

//===================================================================
//	Dynamic attributes related methods
//===================================================================

//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::create_static_attribute_list
 * description : 	Create the a list of static attributes
 *
 * @param	att_list	the ceated attribute list
 */
//--------------------------------------------------------
void SYMBFCleaningClass::create_static_attribute_list(vector<Tango::Attr *> &att_list)
{
	for (unsigned long i=0 ; i<att_list.size() ; i++)
	{
		string att_name(att_list[i]->get_name());
		transform(att_name.begin(), att_name.end(), att_name.begin(), ::tolower);
		defaultAttList.push_back(att_name);
	}

	cout2 << defaultAttList.size() << " attributes in default list" << endl;

	/*----- PROTECTED REGION ID(SYMBFCleaningClass::create_static_att_list) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::create_static_att_list
}


//--------------------------------------------------------
/**
 * method : 		SYMBFCleaningClass::erase_dynamic_attributes
 * description : 	delete the dynamic attributes if any.
 *
 * @param	devlist_ptr	the device list pointer
 * @param	list of all attributes
 */
//--------------------------------------------------------
void SYMBFCleaningClass::erase_dynamic_attributes(const Tango::DevVarStringArray *devlist_ptr, vector<Tango::Attr *> &att_list)
{
	Tango::Util *tg = Tango::Util::instance();

	for (unsigned long i=0 ; i<devlist_ptr->length() ; i++)
	{
		Tango::DeviceImpl *dev_impl = tg->get_device_by_name(((string)(*devlist_ptr)[i]).c_str());
		SYMBFCleaning *dev = static_cast<SYMBFCleaning *> (dev_impl);

		vector<Tango::Attribute *> &dev_att_list = dev->get_device_attr()->get_attribute_list();
		vector<Tango::Attribute *>::iterator ite_att;
		for (ite_att=dev_att_list.begin() ; ite_att != dev_att_list.end() ; ++ite_att)
		{
			string att_name((*ite_att)->get_name_lower());
			if ((att_name == "state") || (att_name == "status"))
				continue;
			vector<string>::iterator ite_str = find(defaultAttList.begin(), defaultAttList.end(), att_name);
			if (ite_str == defaultAttList.end())
			{
				cout2 << att_name << " is a UNWANTED dynamic attribute for device " << (*devlist_ptr)[i] << endl;
				Tango::Attribute &att = dev->get_device_attr()->get_attr_by_name(att_name.c_str());
				dev->remove_attribute(att_list[att.get_attr_idx()], true, false);
				--ite_att;
			}
		}
	}
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::erase_dynamic_attributes) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::erase_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaningClass::get_attr_object_by_name()
 *	Description : returns Tango::Attr * object found by name
 */
//--------------------------------------------------------
Tango::Attr *SYMBFCleaningClass::get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname)
{
	vector<Tango::Attr *>::iterator it;
	for (it=att_list.begin() ; it<att_list.end() ; ++it)
		if ((*it)->get_name()==attname)
			return (*it);
	//	Attr does not exist
	return NULL;
}


/*----- PROTECTED REGION ID(SYMBFCleaningClass::Additional Methods) ENABLED START -----*/

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::Additional Methods
} //	namespace
