/*----- PROTECTED REGION ID(SYMBFCleaningStateMachine.cpp) ENABLED START -----*/
//=============================================================================
//
// file :        SYMBFCleaningStateMachine.cpp
//
// description : State machine file for the SYMBFCleaning class
//
// project :     SyCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <SYMBFCleaning.h>

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SYMBFCleaningStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace SYMBFCleaning_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Phase_allowed()
 *	Description : Execution allowed for Phase attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Phase_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Phase attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::PhaseStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::PhaseStateAllowed_WRITE

	//	Not any excluded states for Phase attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::PhaseStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::PhaseStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_InjectionDelay_allowed()
 *	Description : Execution allowed for InjectionDelay attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_InjectionDelay_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for InjectionDelay attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::InjectionDelayStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::InjectionDelayStateAllowed_WRITE

	//	Not any excluded states for InjectionDelay attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::InjectionDelayStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::InjectionDelayStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_CleaningTime_allowed()
 *	Description : Execution allowed for CleaningTime attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_CleaningTime_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for CleaningTime attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::CleaningTimeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::CleaningTimeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Count_allowed()
 *	Description : Execution allowed for Count attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Count_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Count attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::CountStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::CountStateAllowed_WRITE

	//	Not any excluded states for Count attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::CountStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::CountStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Dwell_allowed()
 *	Description : Execution allowed for Dwell attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Dwell_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Dwell attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::DwellStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::DwellStateAllowed_WRITE

	//	Not any excluded states for Dwell attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::DwellStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::DwellStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Amplitude_allowed()
 *	Description : Execution allowed for Amplitude attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Amplitude_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for Amplitude attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::AmplitudeStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::AmplitudeStateAllowed_WRITE

	//	Not any excluded states for Amplitude attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::AmplitudeStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::AmplitudeStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_UppScrapperPos_allowed()
 *	Description : Execution allowed for UppScrapperPos attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_UppScrapperPos_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for UppScrapperPos attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::UppScrapperPosStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::UppScrapperPosStateAllowed_WRITE

	//	Not any excluded states for UppScrapperPos attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::UppScrapperPosStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::UppScrapperPosStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_LowScrapperPos_allowed()
 *	Description : Execution allowed for LowScrapperPos attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_LowScrapperPos_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for LowScrapperPos attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::LowScrapperPosStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::LowScrapperPosStateAllowed_WRITE

	//	Not any excluded states for LowScrapperPos attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::LowScrapperPosStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::LowScrapperPosStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_PatternDelay_allowed()
 *	Description : Execution allowed for PatternDelay attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_PatternDelay_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for PatternDelay attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::PatternDelayStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::PatternDelayStateAllowed_WRITE

	//	Not any excluded states for PatternDelay attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::PatternDelayStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::PatternDelayStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_SwitchOFFAmplifier_allowed()
 *	Description : Execution allowed for SwitchOFFAmplifier attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_SwitchOFFAmplifier_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for SwitchOFFAmplifier attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::SwitchOFFAmplifierStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SwitchOFFAmplifierStateAllowed_WRITE

	//	Not any excluded states for SwitchOFFAmplifier attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::SwitchOFFAmplifierStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SwitchOFFAmplifierStateAllowed_READ
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_CleaningPattern_allowed()
 *	Description : Execution allowed for CleaningPattern attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_CleaningPattern_allowed(TANGO_UNUSED(Tango::AttReqType type))
{
	//	Not any excluded states for CleaningPattern attribute in Write access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::CleaningPatternStateAllowed_WRITE) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::CleaningPatternStateAllowed_WRITE

	//	Not any excluded states for CleaningPattern attribute in read access.
	/*----- PROTECTED REGION ID(SYMBFCleaning::CleaningPatternStateAllowed_READ) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::CleaningPatternStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_SweepOn_allowed()
 *	Description : Execution allowed for SweepOn attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_SweepOn_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SweepOn command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::SweepOnStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SweepOnStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_SweepOff_allowed()
 *	Description : Execution allowed for SweepOff attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_SweepOff_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for SweepOff command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::SweepOffStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SweepOffStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_EndCleaning_allowed()
 *	Description : Execution allowed for EndCleaning attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_EndCleaning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for EndCleaning command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::EndCleaningStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::EndCleaningStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Stop_allowed()
 *	Description : Execution allowed for Stop attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Stop_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Stop command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::StopStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::StopStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_StartCleaning_allowed()
 *	Description : Execution allowed for StartCleaning attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_StartCleaning_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for StartCleaning command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::StartCleaningStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::StartCleaningStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::is_Reset_allowed()
 *	Description : Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool SYMBFCleaning::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(SYMBFCleaning::ResetStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::ResetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(SYMBFCleaning::SYMBFCleaningStateAllowed.AdditionalMethods) ENABLED START -----*/

//	Additional Methods

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::SYMBFCleaningStateAllowed.AdditionalMethods

}	//	End of namespace
