/*----- PROTECTED REGION ID(SYMBFCleaningClass.h) ENABLED START -----*/
//=============================================================================
//
// file :        SYMBFCleaningClass.h
//
// description : Include for the SYMBFCleaning root class.
//               This class is the singleton class for
//                the SYMBFCleaning device class.
//               It contains all properties and methods which the 
//               SYMBFCleaning requires only once e.g. the commands.
//
// project :     SyCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
//
// Copyright (C): 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef SYMBFCleaningClass_H
#define SYMBFCleaningClass_H

#include <tango.h>
#include <SYMBFCleaning.h>


/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass.h


namespace SYMBFCleaning_ns
{
/*----- PROTECTED REGION ID(SYMBFCleaningClass::classes for dynamic creation) ENABLED START -----*/


/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute ConfigFileName class definition
class ConfigFileNameAttrib: public Tango::Attr
{
public:
	ConfigFileNameAttrib():Attr("ConfigFileName",
			Tango::DEV_STRING, Tango::READ) {};
	~ConfigFileNameAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_ConfigFileName(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_ConfigFileName_allowed(ty);}
};

//	Attribute Phase class definition
class PhaseAttrib: public Tango::Attr
{
public:
	PhaseAttrib():Attr("Phase",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~PhaseAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_Phase(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_Phase(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_Phase_allowed(ty);}
};

//	Attribute InjectionDelay class definition
class InjectionDelayAttrib: public Tango::Attr
{
public:
	InjectionDelayAttrib():Attr("InjectionDelay",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~InjectionDelayAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_InjectionDelay(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_InjectionDelay(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_InjectionDelay_allowed(ty);}
};

//	Attribute CleaningTime class definition
class CleaningTimeAttrib: public Tango::Attr
{
public:
	CleaningTimeAttrib():Attr("CleaningTime",
			Tango::DEV_DOUBLE, Tango::READ) {};
	~CleaningTimeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_CleaningTime(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_CleaningTime_allowed(ty);}
};

//	Attribute Count class definition
class CountAttrib: public Tango::Attr
{
public:
	CountAttrib():Attr("Count",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~CountAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_Count(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_Count(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_Count_allowed(ty);}
};

//	Attribute Dwell class definition
class DwellAttrib: public Tango::Attr
{
public:
	DwellAttrib():Attr("Dwell",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~DwellAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_Dwell(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_Dwell(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_Dwell_allowed(ty);}
};

//	Attribute Amplitude class definition
class AmplitudeAttrib: public Tango::Attr
{
public:
	AmplitudeAttrib():Attr("Amplitude",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~AmplitudeAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_Amplitude(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_Amplitude(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_Amplitude_allowed(ty);}
};

//	Attribute UppScrapperPos class definition
class UppScrapperPosAttrib: public Tango::Attr
{
public:
	UppScrapperPosAttrib():Attr("UppScrapperPos",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~UppScrapperPosAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_UppScrapperPos(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_UppScrapperPos(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_UppScrapperPos_allowed(ty);}
};

//	Attribute LowScrapperPos class definition
class LowScrapperPosAttrib: public Tango::Attr
{
public:
	LowScrapperPosAttrib():Attr("LowScrapperPos",
			Tango::DEV_DOUBLE, Tango::READ_WRITE) {};
	~LowScrapperPosAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_LowScrapperPos(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_LowScrapperPos(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_LowScrapperPos_allowed(ty);}
};

//	Attribute PatternDelay class definition
class PatternDelayAttrib: public Tango::Attr
{
public:
	PatternDelayAttrib():Attr("PatternDelay",
			Tango::DEV_LONG, Tango::READ_WRITE) {};
	~PatternDelayAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_PatternDelay(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_PatternDelay(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_PatternDelay_allowed(ty);}
};

//	Attribute SwitchOFFAmplifier class definition
class SwitchOFFAmplifierAttrib: public Tango::Attr
{
public:
	SwitchOFFAmplifierAttrib():Attr("SwitchOFFAmplifier",
			Tango::DEV_BOOLEAN, Tango::READ_WRITE) {};
	~SwitchOFFAmplifierAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_SwitchOFFAmplifier(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_SwitchOFFAmplifier(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_SwitchOFFAmplifier_allowed(ty);}
};

//	Attribute CleaningPattern class definition
class CleaningPatternAttrib: public Tango::SpectrumAttr
{
public:
	CleaningPatternAttrib():SpectrumAttr("CleaningPattern",
			Tango::DEV_SHORT, Tango::READ_WRITE, 1024) {};
	~CleaningPatternAttrib() {};
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->read_CleaningPattern(att);}
	virtual void write(Tango::DeviceImpl *dev,Tango::WAttribute &att)
		{(static_cast<SYMBFCleaning *>(dev))->write_CleaningPattern(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<SYMBFCleaning *>(dev))->is_CleaningPattern_allowed(ty);}
};


//=========================================
//	Define classes for forwarded attributes
//=========================================
//	Forwarded Attribute Mode class definition
class ModeAttrib: public Tango::FwdAttr
{
public:
	ModeAttrib(const string &_n):FwdAttr(_n) {};
	~ModeAttrib() {};
};

//	Forwarded Attribute Harmonic class definition
class HarmonicAttrib: public Tango::FwdAttr
{
public:
	HarmonicAttrib(const string &_n):FwdAttr(_n) {};
	~HarmonicAttrib() {};
};

//	Forwarded Attribute CentralFreq class definition
class CentralFreqAttrib: public Tango::FwdAttr
{
public:
	CentralFreqAttrib(const string &_n):FwdAttr(_n) {};
	~CentralFreqAttrib() {};
};

//	Forwarded Attribute DeltaFreq class definition
class DeltaFreqAttrib: public Tango::FwdAttr
{
public:
	DeltaFreqAttrib(const string &_n):FwdAttr(_n) {};
	~DeltaFreqAttrib() {};
};


//=========================================
//	Define classes for commands
//=========================================
//	Command GetConfigurationFilePath class definition
class GetConfigurationFilePathClass : public Tango::Command
{
public:
	GetConfigurationFilePathClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	GetConfigurationFilePathClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~GetConfigurationFilePathClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_GetConfigurationFilePath_allowed(any);}
};

//	Command LoadConfigurationFile class definition
class LoadConfigurationFileClass : public Tango::Command
{
public:
	LoadConfigurationFileClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	LoadConfigurationFileClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~LoadConfigurationFileClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_LoadConfigurationFile_allowed(any);}
};

//	Command SaveConfigurationFile class definition
class SaveConfigurationFileClass : public Tango::Command
{
public:
	SaveConfigurationFileClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SaveConfigurationFileClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SaveConfigurationFileClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_SaveConfigurationFile_allowed(any);}
};

//	Command SweepOn class definition
class SweepOnClass : public Tango::Command
{
public:
	SweepOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SweepOnClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SweepOnClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_SweepOn_allowed(any);}
};

//	Command SweepOff class definition
class SweepOffClass : public Tango::Command
{
public:
	SweepOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	SweepOffClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~SweepOffClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_SweepOff_allowed(any);}
};

//	Command EndCleaning class definition
class EndCleaningClass : public Tango::Command
{
public:
	EndCleaningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	EndCleaningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~EndCleaningClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_EndCleaning_allowed(any);}
};

//	Command Stop class definition
class StopClass : public Tango::Command
{
public:
	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StopClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StopClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_Stop_allowed(any);}
};

//	Command StartCleaning class definition
class StartCleaningClass : public Tango::Command
{
public:
	StartCleaningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	StartCleaningClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~StartCleaningClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_StartCleaning_allowed(any);}
};

//	Command Reset class definition
class ResetClass : public Tango::Command
{
public:
	ResetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(name,in,out,in_desc,out_desc, level)	{};

	ResetClass(const char   *name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(name,in,out)	{};
	~ResetClass() {};
	
	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<SYMBFCleaning *>(dev))->is_Reset_allowed(any);}
};


/**
 *	The SYMBFCleaningClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  SYMBFCleaningClass : public Tango::DeviceClass
#else
class SYMBFCleaningClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(SYMBFCleaningClass::Additionnal DServer data members) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaningClass::Additionnal DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
	
		//	Method prototypes
		static SYMBFCleaningClass *init(const char *);
		static SYMBFCleaningClass *instance();
		~SYMBFCleaningClass();
		Tango::DbDatum	get_class_property(string &);
		Tango::DbDatum	get_default_device_property(string &);
		Tango::DbDatum	get_default_class_property(string &);
	
	protected:
		SYMBFCleaningClass(string &);
		static SYMBFCleaningClass *_instance;
		void command_factory();
		void attribute_factory(vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		string get_cvstag();
		string get_cvsroot();
	
	private:
		void device_factory(const Tango::DevVarStringArray *);
		void create_static_attribute_list(vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,vector<Tango::Attr *> &);
		vector<string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(vector<Tango::Attr *> &att_list, string attname);
};

}	//	End of namespace

#endif   //	SYMBFCleaning_H
