/*----- PROTECTED REGION ID(SYMBFCleaning.h) ENABLED START -----*/
//=============================================================================
//
// file :        SYMBFCleaning.h
//
// description : Include file for the SYMBFCleaning class
//
// project :     SYMBFCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Copyright (C): 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef SYMBFCleaning_H
#define SYMBFCleaning_H

#include <tango.h>

const Tango::DevLong pulseValues[] = {1,3,7,15,31};


/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning.h

/**
 *  SYMBFCleaning class description:
 *    A class to handle resonant cleaning in the booster
 */

namespace SYMBFCleaning_ns
{
/*----- PROTECTED REGION ID(SYMBFCleaning::Additional Class Declarations) ENABLED START -----*/

//	Additional Class Declarations

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::Additional Class Declarations

class SYMBFCleaning : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(SYMBFCleaning::Data Members) ENABLED START -----*/

//	Add your own data members

public:

	char configFile[256];
	omni_mutex mutex;
	int sequence_running;
	string sequence_error;
  Tango::DeviceProxy *mbfDs;
  Tango::DeviceProxy *utcaDs;
  Tango::DeviceProxy *phaseDs;
  Tango::DeviceProxy *delayDs;
  Tango::DeviceProxy *amp1Ds;
  Tango::DeviceProxy *amp2Ds;
  Tango::DeviceProxy *uppDs;
  Tango::DeviceProxy *lowDs;
  Tango::DeviceProxy *self;
  string phaseAttName;
  string delayAttName;
  bool abortRequest;

	void write_att(string attName,string value);
  void save_attribute_property(string attName,string propName,double value);
  void split(vector<string> &tokens, const string &text, char sep);
  void update_configfile_name(char *fileName);
  Tango::DevState getShakerState();
  double read_att(string attName);

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::Data Members

//	Device property data members
public:
	//	EpicsName:	Name of the MBF Epics device
	string	epicsName;
	//	MBFName:	Name of MBFControl device
	string	mBFName;
	//	VPhaseAttName:	Name of the VPahe attribue
	string	vPhaseAttName;
	//	InjectionDelayAttName:	Name of the Injection Delay attribute
	string	injectionDelayAttName;
	//	UppScrapperName:	Name of the Upp scrapper device name
	string	uppScrapperName;
	//	LowScrapperName:	Name of the low scrapper device name
	string	lowScrapperName;
	//	Ampli1Name:	Name of the Ampli1 device
	string	ampli1Name;
	//	Ampli2Name:	Name of the Ampli2 device
	string	ampli2Name;
	//	SettingsFilesPath:	Path were are stored settings file
	string	settingsFilesPath;
	//	LastLoaded:	Last loaded file
	string	lastLoaded;

	bool	mandatoryNotDefined;

//	Attribute data members
public:
	Tango::DevString	*attr_ConfigFileName_read;
	Tango::DevDouble	*attr_Phase_read;
	Tango::DevDouble	*attr_InjectionDelay_read;
	Tango::DevDouble	*attr_CleaningTime_read;
	Tango::DevLong	*attr_Count_read;
	Tango::DevLong	*attr_Dwell_read;
	Tango::DevDouble	*attr_Amplitude_read;
	Tango::DevDouble	*attr_UppScrapperPos_read;
	Tango::DevDouble	*attr_LowScrapperPos_read;
	Tango::DevLong	*attr_PatternDelay_read;
	Tango::DevBoolean	*attr_SwitchOFFAmplifier_read;
	Tango::DevShort	*attr_CleaningPattern_read;

//	Constructors and destructors
public:
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SYMBFCleaning(Tango::DeviceClass *cl,string &s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device Name
	 */
	SYMBFCleaning(Tango::DeviceClass *cl,const char *s);
	/**
	 * Constructs a newly device object.
	 *
	 *	@param cl	Class.
	 *	@param s 	Device name
	 *	@param d	Device description.
	 */
	SYMBFCleaning(Tango::DeviceClass *cl,const char *s,const char *d);
	/**
	 * The device object destructor.
	 */
	~SYMBFCleaning() {delete_device();};


//	Miscellaneous methods
public:
	/*
	 *	will be called at device destruction or at init command.
	 */
	void delete_device();
	/*
	 *	Initialize the device
	 */
	virtual void init_device();
	/*
	 *	Read the device properties from database
	 */
	void get_device_property();
	/*
	 *	Always executed method before execution command method.
	 */
	virtual void always_executed_hook();

	/*
	 *	Check if mandatory property has been set
	 */
	 void check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop);

//	Attribute methods
public:
	//--------------------------------------------------------
	/*
	 *	Method      : SYMBFCleaning::read_attr_hardware()
	 *	Description : Hardware acquisition for attributes.
	 */
	//--------------------------------------------------------
	virtual void read_attr_hardware(vector<long> &attr_list);
	//--------------------------------------------------------
	/*
	 *	Method      : SYMBFCleaning::write_attr_hardware()
	 *	Description : Hardware writing for attributes.
	 */
	//--------------------------------------------------------
	virtual void write_attr_hardware(vector<long> &attr_list);

/**
 *	Attribute ConfigFileName related methods
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
	virtual void read_ConfigFileName(Tango::Attribute &attr);
	virtual bool is_ConfigFileName_allowed(Tango::AttReqType type);
/**
 *	Attribute Phase related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Phase(Tango::Attribute &attr);
	virtual void write_Phase(Tango::WAttribute &attr);
	virtual bool is_Phase_allowed(Tango::AttReqType type);
/**
 *	Attribute InjectionDelay related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_InjectionDelay(Tango::Attribute &attr);
	virtual void write_InjectionDelay(Tango::WAttribute &attr);
	virtual bool is_InjectionDelay_allowed(Tango::AttReqType type);
/**
 *	Attribute CleaningTime related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_CleaningTime(Tango::Attribute &attr);
	virtual bool is_CleaningTime_allowed(Tango::AttReqType type);
/**
 *	Attribute Count related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_Count(Tango::Attribute &attr);
	virtual void write_Count(Tango::WAttribute &attr);
	virtual bool is_Count_allowed(Tango::AttReqType type);
/**
 *	Attribute Dwell related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_Dwell(Tango::Attribute &attr);
	virtual void write_Dwell(Tango::WAttribute &attr);
	virtual bool is_Dwell_allowed(Tango::AttReqType type);
/**
 *	Attribute Amplitude related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_Amplitude(Tango::Attribute &attr);
	virtual void write_Amplitude(Tango::WAttribute &attr);
	virtual bool is_Amplitude_allowed(Tango::AttReqType type);
/**
 *	Attribute UppScrapperPos related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_UppScrapperPos(Tango::Attribute &attr);
	virtual void write_UppScrapperPos(Tango::WAttribute &attr);
	virtual bool is_UppScrapperPos_allowed(Tango::AttReqType type);
/**
 *	Attribute LowScrapperPos related methods
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
	virtual void read_LowScrapperPos(Tango::Attribute &attr);
	virtual void write_LowScrapperPos(Tango::WAttribute &attr);
	virtual bool is_LowScrapperPos_allowed(Tango::AttReqType type);
/**
 *	Attribute PatternDelay related methods
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
	virtual void read_PatternDelay(Tango::Attribute &attr);
	virtual void write_PatternDelay(Tango::WAttribute &attr);
	virtual bool is_PatternDelay_allowed(Tango::AttReqType type);
/**
 *	Attribute SwitchOFFAmplifier related methods
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
	virtual void read_SwitchOFFAmplifier(Tango::Attribute &attr);
	virtual void write_SwitchOFFAmplifier(Tango::WAttribute &attr);
	virtual bool is_SwitchOFFAmplifier_allowed(Tango::AttReqType type);
/**
 *	Attribute CleaningPattern related methods
 *	Description: 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Spectrum max = 1024
 */
	virtual void read_CleaningPattern(Tango::Attribute &attr);
	virtual void write_CleaningPattern(Tango::WAttribute &attr);
	virtual bool is_CleaningPattern_allowed(Tango::AttReqType type);


	//--------------------------------------------------------
	/**
	 *	Method      : SYMBFCleaning::add_dynamic_attributes()
	 *	Description : Add dynamic attributes if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_attributes();




//	Command related methods
public:
	/**
	 *	Command State related method
	 *	Description: This command gets the device state (stored in its device_state data member) and returns it to the caller.
	 *
	 *	@returns Device state
	 */
	virtual Tango::DevState dev_state();
	/**
	 *	Command GetConfigurationFilePath related method
	 *	Description: Return configuration file path
	 *
	 *	@returns Configuration file path
	 */
	virtual Tango::DevString get_configuration_file_path();
	virtual bool is_GetConfigurationFilePath_allowed(const CORBA::Any &any);
	/**
	 *	Command LoadConfigurationFile related method
	 *	Description: 
	 *
	 *	@param argin Configuration file name (without the path)
	 */
	virtual void load_configuration_file(Tango::DevString argin);
	virtual bool is_LoadConfigurationFile_allowed(const CORBA::Any &any);
	/**
	 *	Command SaveConfigurationFile related method
	 *	Description: 
	 *
	 *	@param argin Configuration file name (without the path)
	 */
	virtual void save_configuration_file(Tango::DevString argin);
	virtual bool is_SaveConfigurationFile_allowed(const CORBA::Any &any);
	/**
	 *	Command SweepOn related method
	 *	Description: Start sweep (Sweep from freqmin to freqmax)
	 *
	 */
	virtual void sweep_on();
	virtual bool is_SweepOn_allowed(const CORBA::Any &any);
	/**
	 *	Command SweepOff related method
	 *	Description: Stop shaker
	 *
	 */
	virtual void sweep_off();
	virtual bool is_SweepOff_allowed(const CORBA::Any &any);
	/**
	 *	Command EndCleaning related method
	 *	Description: End the cleaning (restore scraper positions)
	 *
	 */
	virtual void end_cleaning();
	virtual bool is_EndCleaning_allowed(const CORBA::Any &any);
	/**
	 *	Command Stop related method
	 *	Description: Stops the cleaning
	 *
	 */
	virtual void stop();
	virtual bool is_Stop_allowed(const CORBA::Any &any);
	/**
	 *	Command StartCleaning related method
	 *	Description: Start the cleaning (preset scraper positions)
	 *
	 */
	virtual void start_cleaning();
	virtual bool is_StartCleaning_allowed(const CORBA::Any &any);
	/**
	 *	Command Reset related method
	 *	Description: Send reset to MBF
	 *
	 */
	virtual void reset();
	virtual bool is_Reset_allowed(const CORBA::Any &any);


	//--------------------------------------------------------
	/**
	 *	Method      : SYMBFCleaning::add_dynamic_commands()
	 *	Description : Add dynamic commands if any.
	 */
	//--------------------------------------------------------
	void add_dynamic_commands();

/*----- PROTECTED REGION ID(SYMBFCleaning::Additional Method prototypes) ENABLED START -----*/

//	Additional Method prototypes

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::Additional Method prototypes
};

/*----- PROTECTED REGION ID(SYMBFCleaning::Additional Classes Definitions) ENABLED START -----*/

//	Additional Classes Definitions

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::Additional Classes Definitions

}	//	End of namespace

#endif   //	SYMBFCleaning_H
