/*----- PROTECTED REGION ID(SYMBFCleaning.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SYMBFCleaning.cpp
//
// description : C++ source for the SYMBFCleaning class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               SYMBFCleaning are implemented in this file.
//
// project :     SYMBFCleaning
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
// Copyright (C): 2004,2005,2006,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
//                European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                France
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SYMBFCleaning.h>
#include <SYMBFCleaningClass.h>
#include <ScraperUpThread.h>
#include <ScraperDownThread.h>
#include <SweepThread.h>

#define RAISE_EXCEPTION(cmd) Tango::Except::throw_exception(\
(const char *)"SYMBFCleaning::error",\
(const char *)cmd,\
(const char *)"SYMBFCleaning::raise");

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning.cpp

/**
 *  SYMBFCleaning class description:
 *    A class to handle resonant cleaning in the booster
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name              |  Method name
//================================================================
//  State                     |  dev_state
//  Status                    |  Inherited (no method)
//  GetConfigurationFilePath  |  get_configuration_file_path
//  LoadConfigurationFile     |  load_configuration_file
//  SaveConfigurationFile     |  save_configuration_file
//  SweepOn                   |  sweep_on
//  SweepOff                  |  sweep_off
//  EndCleaning               |  end_cleaning
//  Stop                      |  stop
//  StartCleaning             |  start_cleaning
//  Reset                     |  reset
//================================================================

//================================================================
//  Attributes managed are:
//================================================================
//  ConfigFileName      |  Tango::DevString	Scalar
//  Phase               |  Tango::DevDouble	Scalar
//  InjectionDelay      |  Tango::DevDouble	Scalar
//  CleaningTime        |  Tango::DevDouble	Scalar
//  Count               |  Tango::DevLong	Scalar
//  Dwell               |  Tango::DevLong	Scalar
//  Amplitude           |  Tango::DevDouble	Scalar
//  UppScrapperPos      |  Tango::DevDouble	Scalar
//  LowScrapperPos      |  Tango::DevDouble	Scalar
//  PatternDelay        |  Tango::DevLong	Scalar
//  SwitchOFFAmplifier  |  Tango::DevBoolean	Scalar
//  CleaningPattern     |  Tango::DevShort	Spectrum  ( max = 1024)
//================================================================

namespace SYMBFCleaning_ns
{
/*----- PROTECTED REGION ID(SYMBFCleaning::namespace_starting) ENABLED START -----*/

//	static initializations

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::namespace_starting

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::SYMBFCleaning()
 *	Description : Constructors for a Tango device
 *                implementing the classSYMBFCleaning
 */
//--------------------------------------------------------
SYMBFCleaning::SYMBFCleaning(Tango::DeviceClass *cl, string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::constructor_1) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::constructor_1
}
//--------------------------------------------------------
SYMBFCleaning::SYMBFCleaning(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::constructor_2) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::constructor_2
}
//--------------------------------------------------------
SYMBFCleaning::SYMBFCleaning(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::constructor_3) ENABLED START -----*/
	init_device();
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::constructor_3
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::delete_device()
 *	Description : will be called at device destruction or at init command
 */
//--------------------------------------------------------
void SYMBFCleaning::delete_device()
{
	DEBUG_STREAM << "SYMBFCleaning::delete_device() " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::delete_device) ENABLED START -----*/
	
	//	Delete device allocated objects
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::delete_device
	delete[] attr_ConfigFileName_read;
	delete[] attr_Phase_read;
	delete[] attr_InjectionDelay_read;
	delete[] attr_CleaningTime_read;
	delete[] attr_Count_read;
	delete[] attr_Dwell_read;
	delete[] attr_Amplitude_read;
	delete[] attr_UppScrapperPos_read;
	delete[] attr_LowScrapperPos_read;
	delete[] attr_PatternDelay_read;
	delete[] attr_SwitchOFFAmplifier_read;
	delete[] attr_CleaningPattern_read;
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::init_device()
 *	Description : will be called at device initialization.
 */
//--------------------------------------------------------
void SYMBFCleaning::init_device()
{
	DEBUG_STREAM << "SYMBFCleaning::init_device() create device " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::init_device_before) ENABLED START -----*/
	
	//	Initialization before get_device_property() call
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::init_device_before
	

	//	Get the device properties from database
	get_device_property();
	
	attr_ConfigFileName_read = new Tango::DevString[1];
	attr_Phase_read = new Tango::DevDouble[1];
	attr_InjectionDelay_read = new Tango::DevDouble[1];
	attr_CleaningTime_read = new Tango::DevDouble[1];
	attr_Count_read = new Tango::DevLong[1];
	attr_Dwell_read = new Tango::DevLong[1];
	attr_Amplitude_read = new Tango::DevDouble[1];
	attr_UppScrapperPos_read = new Tango::DevDouble[1];
	attr_LowScrapperPos_read = new Tango::DevDouble[1];
	attr_PatternDelay_read = new Tango::DevLong[1];
	attr_SwitchOFFAmplifier_read = new Tango::DevBoolean[1];
	attr_CleaningPattern_read = new Tango::DevShort[1024];
	//	No longer if mandatory property not set. 
	if (mandatoryNotDefined)
		return;

	/*----- PROTECTED REGION ID(SYMBFCleaning::init_device) ENABLED START -----*/
	
	//	Initialize device
	strcpy(configFile,"No file loaded");
	attr_Phase_read[0]=0.0;
	attr_InjectionDelay_read[0]=0.0;
	attr_CleaningTime_read[0]=0.0;
  attr_Amplitude_read[0]=1;
  attr_PatternDelay_read[0] = 0;
  attr_UppScrapperPos_read[0]=0.0;
  attr_LowScrapperPos_read[0]=0.0;
  attr_Count_read[0]=0;
  attr_Dwell_read[0]=0;
  attr_SwitchOFFAmplifier_read[0] = false;
  memset(attr_CleaningPattern_read,0,sizeof(Tango::DevShort)*1024);
	sequence_running = false;
	sequence_error = "";
	set_state(Tango::UNKNOWN);

	if( epicsName.length()==0 ) {
	  cerr << "EpicsName device property not defined" << endl;
	  exit(0);
	}
  if( mBFName.length()==0 ) {
    cerr << "MBFName device property not defined" << endl;
    exit(0);
  }
	if( ampli1Name.length()==0 ) {
	  cerr << "Ampli1Name device property not defined" << endl;
	  exit(0);
	}
	if( ampli2Name.length()==0 ) {
	  cerr << "Ampli2Name device property not defined" << endl;
	  exit(0);
	}
  if( vPhaseAttName.length()==0 ) {
    cerr << "VPhaseAttName device property not defined" << endl;
    exit(0);
  }
  if( injectionDelayAttName.length()==0 ) {
    cerr << "InjectionDelayAttName device property not defined" << endl;
    exit(0);
  }
  if( settingsFilesPath.length()==0 ) {
    cerr << "SettingsFilesPath device property not defined" << endl;
    exit(0);
  }
	if( lowScrapperName.length()==0 ) {
	  cerr << "LowScrapperName device property not defined" << endl;
	  exit(0);
	}
  if( uppScrapperName.length()==0 ) {
    cerr << "uppScrapperName device property not defined" << endl;
    exit(0);
  }

  utcaDs = new Tango::DeviceProxy(epicsName);
  mbfDs = new Tango::DeviceProxy(mBFName);
  amp1Ds = new Tango::DeviceProxy(ampli1Name);
  amp2Ds = new Tango::DeviceProxy(ampli2Name);
  vector<string> fields;

  split(fields,vPhaseAttName,'/');
  if(fields.size()!=4) {
    cerr << "VPHaseAttName device property 4 field expected" << endl;
    exit(0);
  }
  string phaseDevName = fields[0] + "/" + fields[1] + "/" + fields[2];
  phaseAttName = fields[3];

  split(fields,injectionDelayAttName,'/');
  if(fields.size()!=4) {
    cerr << "InjectionDelayAttName device property 4 field expected" << endl;
    exit(0);
  }
  string delayDevName = fields[0] + "/" + fields[1] + "/" + fields[2];
  delayAttName = fields[3];

  phaseDs = new Tango::DeviceProxy(phaseDevName);
  delayDs = new Tango::DeviceProxy(delayDevName);
  uppDs = new Tango::DeviceProxy(uppScrapperName);
  lowDs = new Tango::DeviceProxy(lowScrapperName);
  self = new Tango::DeviceProxy(get_name());

  utcaDs->set_source(Tango::DEV);
  delayDs->set_source(Tango::DEV);
  amp1Ds->set_source(Tango::DEV);
  amp2Ds->set_source(Tango::DEV);
  phaseDs->set_source(Tango::DEV);
  lowDs->set_source(Tango::DEV);
  uppDs->set_source(Tango::DEV);

  strcpy(configFile,lastLoaded.c_str());

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::init_device
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::get_device_property()
 *	Description : Read database to initialize property data members.
 */
//--------------------------------------------------------
void SYMBFCleaning::get_device_property()
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::get_device_property_before) ENABLED START -----*/
	
	//	Initialize property data members
  epicsName = "";
	ampli1Name = "";
	ampli2Name = "";
	settingsFilesPath = "";
  vPhaseAttName = "";
  lowScrapperName = "";
  uppScrapperName = "";
  injectionDelayAttName = "";
  lastLoaded = "No file loaded";

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::get_device_property_before

	mandatoryNotDefined = false;

	//	Read device properties from database.
	Tango::DbData	dev_prop;
	dev_prop.push_back(Tango::DbDatum("EpicsName"));
	dev_prop.push_back(Tango::DbDatum("MBFName"));
	dev_prop.push_back(Tango::DbDatum("VPhaseAttName"));
	dev_prop.push_back(Tango::DbDatum("InjectionDelayAttName"));
	dev_prop.push_back(Tango::DbDatum("UppScrapperName"));
	dev_prop.push_back(Tango::DbDatum("LowScrapperName"));
	dev_prop.push_back(Tango::DbDatum("Ampli1Name"));
	dev_prop.push_back(Tango::DbDatum("Ampli2Name"));
	dev_prop.push_back(Tango::DbDatum("SettingsFilesPath"));
	dev_prop.push_back(Tango::DbDatum("LastLoaded"));

	//	is there at least one property to be read ?
	if (dev_prop.size()>0)
	{
		//	Call database and extract values
		if (Tango::Util::instance()->_UseDb==true)
			get_db_device()->get_property(dev_prop);
	
		//	get instance on SYMBFCleaningClass to get class property
		Tango::DbDatum	def_prop, cl_prop;
		SYMBFCleaningClass	*ds_class =
			(static_cast<SYMBFCleaningClass *>(get_device_class()));
		int	i = -1;

		//	Try to initialize EpicsName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  epicsName;
		else {
			//	Try to initialize EpicsName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  epicsName;
		}
		//	And try to extract EpicsName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  epicsName;

		//	Try to initialize MBFName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  mBFName;
		else {
			//	Try to initialize MBFName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  mBFName;
		}
		//	And try to extract MBFName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  mBFName;

		//	Try to initialize VPhaseAttName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  vPhaseAttName;
		else {
			//	Try to initialize VPhaseAttName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  vPhaseAttName;
		}
		//	And try to extract VPhaseAttName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  vPhaseAttName;

		//	Try to initialize InjectionDelayAttName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  injectionDelayAttName;
		else {
			//	Try to initialize InjectionDelayAttName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  injectionDelayAttName;
		}
		//	And try to extract InjectionDelayAttName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  injectionDelayAttName;

		//	Try to initialize UppScrapperName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  uppScrapperName;
		else {
			//	Try to initialize UppScrapperName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  uppScrapperName;
		}
		//	And try to extract UppScrapperName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  uppScrapperName;

		//	Try to initialize LowScrapperName from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  lowScrapperName;
		else {
			//	Try to initialize LowScrapperName from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  lowScrapperName;
		}
		//	And try to extract LowScrapperName value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  lowScrapperName;
		//	Property StartDsPath is mandatory, check if has been defined in database.
		check_mandatory_property(cl_prop, dev_prop[i]);

		//	Try to initialize Ampli1Name from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  ampli1Name;
		else {
			//	Try to initialize Ampli1Name from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  ampli1Name;
		}
		//	And try to extract Ampli1Name value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  ampli1Name;

		//	Try to initialize Ampli2Name from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  ampli2Name;
		else {
			//	Try to initialize Ampli2Name from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  ampli2Name;
		}
		//	And try to extract Ampli2Name value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  ampli2Name;

		//	Try to initialize SettingsFilesPath from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  settingsFilesPath;
		else {
			//	Try to initialize SettingsFilesPath from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  settingsFilesPath;
		}
		//	And try to extract SettingsFilesPath value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  settingsFilesPath;

		//	Try to initialize LastLoaded from class property
		cl_prop = ds_class->get_class_property(dev_prop[++i].name);
		if (cl_prop.is_empty()==false)	cl_prop  >>  lastLoaded;
		else {
			//	Try to initialize LastLoaded from default device value
			def_prop = ds_class->get_default_device_property(dev_prop[i].name);
			if (def_prop.is_empty()==false)	def_prop  >>  lastLoaded;
		}
		//	And try to extract LastLoaded value from database
		if (dev_prop[i].is_empty()==false)	dev_prop[i]  >>  lastLoaded;

	}

	/*----- PROTECTED REGION ID(SYMBFCleaning::get_device_property_after) ENABLED START -----*/
	
	//	Check device property data members init
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::get_device_property_after
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::check_mandatory_property()
 *	Description : For mandatory properties check if defined in database.
 */
//--------------------------------------------------------
void SYMBFCleaning::check_mandatory_property(Tango::DbDatum &class_prop, Tango::DbDatum &dev_prop)
{
	//	Check if all properties are empty
	if (class_prop.is_empty() && dev_prop.is_empty())
	{
		TangoSys_OMemStream	tms;
		tms << endl <<"Property \'" << dev_prop.name;
		if (Tango::Util::instance()->_UseDb==true)
			tms << "\' is mandatory but not defined in database";
		else
			tms << "\' is mandatory but cannot be defined without database";
		append_status(tms.str());
		mandatoryNotDefined = true;
		/*----- PROTECTED REGION ID(SYMBFCleaning::check_mandatory_property) ENABLED START -----*/
		cerr << tms.str() << " for " << device_name << endl;
		
		/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::check_mandatory_property
	}
}


//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::always_executed_hook()
 *	Description : method always executed before any command is executed
 */
//--------------------------------------------------------
void SYMBFCleaning::always_executed_hook()
{
	DEBUG_STREAM << "SYMBFCleaning::always_executed_hook()  " << device_name << endl;
	if (mandatoryNotDefined)
	{
		Tango::Except::throw_exception(
					(const char *)"PROPERTY_NOT_SET",
					get_status().c_str(),
					(const char *)"SYMBFCleaning::always_executed_hook()");
	}
	/*----- PROTECTED REGION ID(SYMBFCleaning::always_executed_hook) ENABLED START -----*/
	
	//	code always executed before all requests
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::always_executed_hook
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::read_attr_hardware()
 *	Description : Hardware acquisition for attributes
 */
//--------------------------------------------------------
void SYMBFCleaning::read_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "SYMBFCleaning::read_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_attr_hardware
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::write_attr_hardware()
 *	Description : Hardware writing for attributes
 */
//--------------------------------------------------------
void SYMBFCleaning::write_attr_hardware(TANGO_UNUSED(vector<long> &attr_list))
{
	DEBUG_STREAM << "SYMBFCleaning::write_attr_hardware(vector<long> &attr_list) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_attr_hardware) ENABLED START -----*/
	
	//	Add your own code
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_attr_hardware
}

//--------------------------------------------------------
/**
 *	Read attribute ConfigFileName related method
 *	Description: 
 *
 *	Data type:	Tango::DevString
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_ConfigFileName(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_ConfigFileName(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_ConfigFileName) ENABLED START -----*/
	//	Set the attribute value
	attr_ConfigFileName_read[0] = configFile;
  attr.set_value(attr_ConfigFileName_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_ConfigFileName
}
//--------------------------------------------------------
/**
 *	Read attribute Phase related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_Phase(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_Phase(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_Phase) ENABLED START -----*/
	attr.set_value(attr_Phase_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_Phase
}
//--------------------------------------------------------
/**
 *	Write attribute Phase related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_Phase(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_Phase(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_Phase) ENABLED START -----*/
	Tango::DeviceAttribute da(phaseAttName,(Tango::DevFloat)w_val);
	phaseDs->write_attribute(da);
  attr_Phase_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_Phase
}
//--------------------------------------------------------
/**
 *	Read attribute InjectionDelay related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_InjectionDelay(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_InjectionDelay(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_InjectionDelay) ENABLED START -----*/
	attr.set_value(attr_InjectionDelay_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_InjectionDelay
}
//--------------------------------------------------------
/**
 *	Write attribute InjectionDelay related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_InjectionDelay(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_InjectionDelay(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_InjectionDelay) ENABLED START -----*/
  Tango::DeviceAttribute da(delayAttName,(Tango::DevDouble)w_val);
  delayDs->write_attribute(da);
  attr_InjectionDelay_read[0] = w_val;
  /*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_InjectionDelay
}
//--------------------------------------------------------
/**
 *	Read attribute CleaningTime related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_CleaningTime(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_CleaningTime(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_CleaningTime) ENABLED START -----*/
  Tango::DeviceAttribute da = utcaDs->read_attribute("SEQ_DURATION_S");
  da >> attr_CleaningTime_read[0];
  attr_CleaningTime_read[0] *= 1000.0;
	attr.set_value(attr_CleaningTime_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_CleaningTime
}
//--------------------------------------------------------
/**
 *	Read attribute Count related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_Count(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_Count(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_Count) ENABLED START -----*/
	attr.set_value(attr_Count_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_Count
}
//--------------------------------------------------------
/**
 *	Write attribute Count related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_Count(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_Count(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_Count) ENABLED START -----*/
  Tango::DeviceAttribute da("SEQ_1_COUNT_S",(Tango::DevLong)w_val);
  utcaDs->write_attribute(da);
  attr_Count_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_Count
}
//--------------------------------------------------------
/**
 *	Read attribute Dwell related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_Dwell(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_Dwell(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_Dwell) ENABLED START -----*/
	attr.set_value(attr_Dwell_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_Dwell
}
//--------------------------------------------------------
/**
 *	Write attribute Dwell related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_Dwell(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_Dwell(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_Dwell) ENABLED START -----*/
  Tango::DeviceAttribute da("SEQ_1_DWELL_S",(Tango::DevLong)w_val);
  utcaDs->write_attribute(da);
  attr_Dwell_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_Dwell
}
//--------------------------------------------------------
/**
 *	Read attribute Amplitude related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_Amplitude(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_Amplitude(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_Amplitude) ENABLED START -----*/
	attr.set_value(attr_Amplitude_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_Amplitude
}
//--------------------------------------------------------
/**
 *	Write attribute Amplitude related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_Amplitude(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_Amplitude(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_Amplitude) ENABLED START -----*/
  Tango::DeviceAttribute da("SEQ_1_GAIN_SCALAR_S",(Tango::DevDouble)w_val);
  utcaDs->write_attribute(da);
  attr_Amplitude_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_Amplitude
}
//--------------------------------------------------------
/**
 *	Read attribute UppScrapperPos related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_UppScrapperPos(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_UppScrapperPos(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_UppScrapperPos) ENABLED START -----*/
	attr.set_value(attr_UppScrapperPos_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_UppScrapperPos
}
//--------------------------------------------------------
/**
 *	Write attribute UppScrapperPos related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_UppScrapperPos(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_UppScrapperPos(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_UppScrapperPos) ENABLED START -----*/
  attr_UppScrapperPos_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_UppScrapperPos
}
//--------------------------------------------------------
/**
 *	Read attribute LowScrapperPos related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_LowScrapperPos(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_LowScrapperPos(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_LowScrapperPos) ENABLED START -----*/
	attr.set_value(attr_LowScrapperPos_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_LowScrapperPos
}
//--------------------------------------------------------
/**
 *	Write attribute LowScrapperPos related method
 *	Description: 
 *
 *	Data type:	Tango::DevDouble
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_LowScrapperPos(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_LowScrapperPos(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevDouble	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_LowScrapperPos) ENABLED START -----*/
  attr_LowScrapperPos_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_LowScrapperPos
}
//--------------------------------------------------------
/**
 *	Read attribute PatternDelay related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_PatternDelay(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_PatternDelay(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_PatternDelay) ENABLED START -----*/
	attr.set_value(attr_PatternDelay_read);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_PatternDelay
}
//--------------------------------------------------------
/**
 *	Write attribute PatternDelay related method
 *	Description: 
 *
 *	Data type:	Tango::DevLong
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_PatternDelay(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_PatternDelay(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevLong	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_PatternDelay) ENABLED START -----*/
  Tango::DeviceAttribute da("DAC_DELAY_S",(Tango::DevLong)w_val);
  utcaDs->write_attribute(da);
  attr_PatternDelay_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_PatternDelay
}
//--------------------------------------------------------
/**
 *	Read attribute SwitchOFFAmplifier related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::read_SwitchOFFAmplifier(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_SwitchOFFAmplifier(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_SwitchOFFAmplifier) ENABLED START -----*/
	//	Set the attribute value
	attr.set_value(attr_SwitchOFFAmplifier_read);
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_SwitchOFFAmplifier
}
//--------------------------------------------------------
/**
 *	Write attribute SwitchOFFAmplifier related method
 *	Description: 
 *
 *	Data type:	Tango::DevBoolean
 *	Attr type:	Scalar
 */
//--------------------------------------------------------
void SYMBFCleaning::write_SwitchOFFAmplifier(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_SwitchOFFAmplifier(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve write value
	Tango::DevBoolean	w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_SwitchOFFAmplifier) ENABLED START -----*/
  attr_SwitchOFFAmplifier_read[0] = w_val;
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_SwitchOFFAmplifier
}
//--------------------------------------------------------
/**
 *	Read attribute CleaningPattern related method
 *	Description: 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void SYMBFCleaning::read_CleaningPattern(Tango::Attribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::read_CleaningPattern(Tango::Attribute &attr) entering... " << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::read_CleaningPattern) ENABLED START -----*/
	attr.set_value(attr_CleaningPattern_read, 704);
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::read_CleaningPattern
}
//--------------------------------------------------------
/**
 *	Write attribute CleaningPattern related method
 *	Description: 
 *
 *	Data type:	Tango::DevShort
 *	Attr type:	Spectrum max = 1024
 */
//--------------------------------------------------------
void SYMBFCleaning::write_CleaningPattern(Tango::WAttribute &attr)
{
	DEBUG_STREAM << "SYMBFCleaning::write_CleaningPattern(Tango::WAttribute &attr) entering... " << endl;
	//	Retrieve number of write values
	int	w_length = attr.get_write_value_length();

	//	Retrieve pointer on write values (Do not delete !)
	const Tango::DevShort	*w_val;
	attr.get_write_value(w_val);
	/*----- PROTECTED REGION ID(SYMBFCleaning::write_CleaningPattern) ENABLED START -----*/
	if(w_length!=704)  {
    RAISE_EXCEPTION("Cleaning pattern wrong size: 704 expected");
	}
	for(int i=0;i<w_length;i++) attr_CleaningPattern_read[i] = w_val[i];

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::write_CleaningPattern
}

//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::add_dynamic_attributes()
 *	Description : Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void SYMBFCleaning::add_dynamic_attributes()
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::add_dynamic_attributes) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic attributes if any
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *	Command State related method
 *	Description: This command gets the device state (stored in its device_state data member) and returns it to the caller.
 *
 *	@returns Device state
 */
//--------------------------------------------------------
Tango::DevState SYMBFCleaning::dev_state()
{
	DEBUG_STREAM << "SYMBFCleaning::State()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::dev_state) ENABLED START -----*/
	
	Tango::DevState	argout = Tango::UNKNOWN; // replace by your own algorithm

	if( sequence_running ) {
	  set_state(Tango::MOVING);
	  DeviceImpl::dev_state();
	  return get_state();
	}

	if( sequence_error.length()>0 ) {
	  set_state(Tango::FAULT);
	  set_status(sequence_error);
	  DeviceImpl::dev_state();
	  return get_state();
	}

  Tango::DeviceAttribute da;

	da = amp1Ds->read_attribute("Ampli_OnOff");
	Tango::DevBoolean amp1State;
	da >> amp1State;
	
	da = amp2Ds->read_attribute("Ampli_OnOff");
	Tango::DevBoolean amp2State;
	da >> amp2State;

  Tango::DevState shakerState = getShakerState();
  string status = "";

	if( amp1State && amp2State && (shakerState==Tango::ON)) {
	  argout = Tango::ON;
    status = "Cleaning is ON\n";
	} else {
	  argout = Tango::OFF;
    status = "Cleaning is OFF\n";
	}
	if(shakerState==Tango::ON) {
	  status += "Shaker is ON";
	} else {
    status += "Shaker is OFF";
	}
	set_status(status);
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::dev_state
	set_state(argout);    // Give the state to Tango.
	if (argout!=Tango::ALARM)
		Tango::DeviceImpl::dev_state();
	return get_state();  // Return it after Tango management.
}
//--------------------------------------------------------
/**
 *	Command GetConfigurationFilePath related method
 *	Description: Return configuration file path
 *
 *	@returns Configuration file path
 */
//--------------------------------------------------------
Tango::DevString SYMBFCleaning::get_configuration_file_path()
{
	Tango::DevString argout;
	DEBUG_STREAM << "SYMBFCleaning::GetConfigurationFilePath()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::get_configuration_file_path) ENABLED START -----*/

	argout  = new char[settingsFilesPath.length()+1];
	strcpy(argout, settingsFilesPath.c_str());
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::get_configuration_file_path
	return argout;
}
//--------------------------------------------------------
/**
 *	Command LoadConfigurationFile related method
 *	Description: 
 *
 *	@param argin Configuration file name (without the path)
 */
//--------------------------------------------------------
void SYMBFCleaning::load_configuration_file(Tango::DevString argin)
{
	DEBUG_STREAM << "SYMBFCleaning::LoadConfigurationFile()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::load_configuration_file) ENABLED START -----*/
	
	if( get_state()==Tango::MOVING )
	  RAISE_EXCEPTION("Cannot read config file while moving.");

  char absolute_name[512];
  strcpy(absolute_name, settingsFilesPath.c_str());
  strcat(absolute_name, argin);
  char *p = strchr(argin,'.');
  if(p==NULL)
    // Add extension
    strcat(absolute_name,".ts");

  ifstream conf(absolute_name, ios::in);
  if (conf.is_open()) {

    char buffer[8192];
    int line_number = 0;
    int end = 0;

    while(!end) {

      // Read a line from file.
      conf.getline(buffer, 8192);
      line_number++;
      string rd = string(buffer);

      if (rd.length() == 0) {
        // End of file reached
        end = 1;
        continue;
      }

      // Jump comments
      if (rd[0] == '#')
        continue;
      vector<string> fields;
      vector<string> nameFields;

      split(fields, rd, ':');
      if (fields.size() != 2) {
        cerr << "Syntax error at line " << line_number << ": " << absolute_name << endl;
        conf.close();
        RAISE_EXCEPTION("Syntax error in config file, ':' missing");
      }

      split(nameFields, fields[0], '/');
      if (nameFields.size() != 4) {
        cerr << "Syntax error at line " << line_number << ": " << absolute_name << endl;
        conf.close();
        RAISE_EXCEPTION("Syntax error in config file. invalid attribute name");
      }

      string devName = nameFields[0] + "/" + nameFields[1] + "/" + nameFields[2];
      if( strcasecmp(devName.c_str(),get_name().c_str())!=0 ) {
        conf.close();
        RAISE_EXCEPTION("configfile limited to single device");
      }

      try {
        write_att(nameFields[3],fields[1]);
      } catch (Tango::DevFailed &e) {
        conf.close();
        Tango::Except::throw_exception(
          (const char *) "SyCleaning::error", \
          (const char *) (string(e.errors[0].desc) + " " +nameFields[3]).c_str(), \
          (const char *) "SyCleaning::raise");
      }
    }

  } else {

    // Unable to open file.
    char tmp[1024];
    sprintf(tmp,"Unable to open file for reading %s",absolute_name);
    RAISE_EXCEPTION(tmp);

  }

  conf.close();
  update_configfile_name(argin);

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::load_configuration_file
}
//--------------------------------------------------------
/**
 *	Command SaveConfigurationFile related method
 *	Description: 
 *
 *	@param argin Configuration file name (without the path)
 */
//--------------------------------------------------------
void SYMBFCleaning::save_configuration_file(Tango::DevString argin)
{
	DEBUG_STREAM << "SYMBFCleaning::SaveConfigurationFile()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::save_configuration_file) ENABLED START -----*/

	if( get_state()==Tango::MOVING )
	  RAISE_EXCEPTION("Cannot save config file while moving.");

  char absolute_name[1024];
  strcpy(absolute_name, settingsFilesPath.c_str());
  strcat(absolute_name, argin);
  char *p = strchr(argin,'.');
  if(p==NULL)
    // Add extension
    strcat(absolute_name,".ts");

  ofstream conf(absolute_name, ios::out);

  if (conf.is_open()) {

    conf << "# SY cleaning  CONFIG  FILE " << endl;
    conf << "#" << endl;
    conf << get_name() + "/Phase: "          <<  attr_Phase_read[0] << endl;
    conf << get_name() + "/InjectionDelay: " <<  attr_InjectionDelay_read[0] << endl;
    conf << get_name() + "/Dwell: "          <<  attr_Dwell_read[0] << endl;
    conf << get_name() + "/Count: "          <<  attr_Count_read[0] << endl;
    conf << get_name() + "/Harmonic: "       <<  read_att("Harmonic") << endl;
    conf << get_name() + "/DeltaFreq: "      <<  read_att("DeltaFreq") << endl;
    conf << get_name() + "/CentralFreq: "    <<  read_att("CentralFreq") << endl;
    conf << get_name() + "/Amplitude: "      <<  attr_Amplitude_read[0] << endl;
    conf << get_name() + "/UppScrapperPos: " <<  attr_UppScrapperPos_read[0] << endl;
    conf << get_name() + "/LowScrapperPos: " <<  attr_LowScrapperPos_read[0] << endl;
    conf << get_name() + "/SwitchOFFAmplifier: " <<  (int)(attr_SwitchOFFAmplifier_read[0]) << endl;
    conf << get_name() + "/PatternDelay: "   <<  attr_PatternDelay_read[0] << endl;
    /*
    conf << get_name() + "/CleaningPattern: ";
    for(int i=0;i<704;i++) {
      conf << attr_CleaningPattern_read[i];
      if(i<703)
        conf << ",";
    }
    conf << endl;
    */
    conf.close();
    update_configfile_name(argin);


  } else {

    // Unable to create file.
    char tmp[1024];
    sprintf(tmp,"Unable to open file for writing %s",absolute_name);
    RAISE_EXCEPTION(tmp);

  }

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::save_configuration_file
}
//--------------------------------------------------------
/**
 *	Command SweepOn related method
 *	Description: Start sweep (Sweep from freqmin to freqmax)
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::sweep_on()
{
	DEBUG_STREAM << "SYMBFCleaning::SweepOn()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::sweep_on) ENABLED START -----*/

  if( get_state()==Tango::MOVING )
    RAISE_EXCEPTION("Cannot clean while moving.");

  if(attr_CleaningTime_read[0]<=0.0) {
    RAISE_EXCEPTION("SweepTime must be positive");
  }

  set_state(Tango::MOVING);
  set_status("Moving scrapers");
  SweepThread *t = new SweepThread(this, mutex, true);

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::sweep_on
}
//--------------------------------------------------------
/**
 *	Command SweepOff related method
 *	Description: Stop shaker
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::sweep_off()
{
	DEBUG_STREAM << "SYMBFCleaning::SweepOff()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::sweep_off) ENABLED START -----*/
	
  if( get_state()==Tango::MOVING )
    RAISE_EXCEPTION("Cannot clean while moving.");

  set_state(Tango::MOVING);
  set_status("Moving scrapers");
  SweepThread *t = new SweepThread(this, mutex, false);

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::sweep_off
}
//--------------------------------------------------------
/**
 *	Command EndCleaning related method
 *	Description: End the cleaning (restore scraper positions)
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::end_cleaning()
{
	DEBUG_STREAM << "SYMBFCleaning::EndCleaning()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::end_cleaning) ENABLED START -----*/
	
  if( get_state()==Tango::MOVING )
    RAISE_EXCEPTION("Cannot stop cleaning while moving.");

  set_state(Tango::MOVING);
  set_status("Moving scrapers");
  ScraperUpThread *t = new ScraperUpThread(this, mutex);

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::end_cleaning
}
//--------------------------------------------------------
/**
 *	Command Stop related method
 *	Description: Stops the cleaning
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::stop()
{
	DEBUG_STREAM << "SYMBFCleaning::Stop()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::stop) ENABLED START -----*/

  // Abort scraper motion
  uppDs->command_inout("Abort");
  lowDs->command_inout("Abort");
  abortRequest = true;

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::stop
}
//--------------------------------------------------------
/**
 *	Command StartCleaning related method
 *	Description: Start the cleaning (preset scraper positions)
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::start_cleaning()
{
	DEBUG_STREAM << "SYMBFCleaning::StartCleaning()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::start_cleaning) ENABLED START -----*/

  if( get_state()==Tango::MOVING )
    RAISE_EXCEPTION("Cannot stop cleaning while moving.");

  set_state(Tango::MOVING);
  set_status("Moving scrapers");
  ScraperDownThread *t = new ScraperDownThread(this, mutex);

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::start_cleaning
}
//--------------------------------------------------------
/**
 *	Command Reset related method
 *	Description: Send reset to MBF
 *
 */
//--------------------------------------------------------
void SYMBFCleaning::reset()
{
	DEBUG_STREAM << "SYMBFCleaning::Reset()  - " << device_name << endl;
	/*----- PROTECTED REGION ID(SYMBFCleaning::reset) ENABLED START -----*/

	mbfDs->command_inout("Reset");

	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::reset
}
//--------------------------------------------------------
/**
 *	Method      : SYMBFCleaning::add_dynamic_commands()
 *	Description : Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void SYMBFCleaning::add_dynamic_commands()
{
	/*----- PROTECTED REGION ID(SYMBFCleaning::add_dynamic_commands) ENABLED START -----*/
	
	//	Add your own code to create and add dynamic commands if any
	
	/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::add_dynamic_commands
}

/*----- PROTECTED REGION ID(SYMBFCleaning::namespace_ending) ENABLED START -----*/

  void SYMBFCleaning::split(vector<string> &tokens, const string &text, char sep) {

    size_t start = 0, end = 0;
    tokens.clear();

    while ((end = text.find(sep, start)) != string::npos) {
      tokens.push_back(text.substr(start, end - start));
      start = end + 1;
    }

    tokens.push_back(text.substr(start));

  }

  void SYMBFCleaning::update_configfile_name(char *fileName) {
    strcpy(configFile,fileName);
    // Remove extension
    char *p = strrchr(configFile,'.');
    if(p) *p = 0;

    // Save to DB
    Tango::DbDatum dbProp("LastLoaded");
    dbProp << configFile;
    Tango::DbData dbData;
    dbData.push_back(dbProp);
    get_db_device()->put_property(dbData);
  }

  Tango::DevState SYMBFCleaning::getShakerState() {

    Tango::DevState s = Tango::UNKNOWN;
    try {
      Tango::DeviceAttribute da = mbfDs->read_attribute("SweepState");
      da >>s;
    } catch(Tango::DevFailed &e) {
    }

    return s;

  }

  double SYMBFCleaning::read_att(string attName) {
    double ret;
    Tango::DeviceAttribute da = self->read_attribute(attName);
    da >> ret;
    return ret;
  }

  void SYMBFCleaning::write_att(string attName,string value) {

    Tango::WAttribute &att = dev_attr->get_w_attr_by_name(attName.c_str());
    switch( att.get_data_type() ) {
      case Tango::DEV_DOUBLE:
        if(att.get_data_format()==Tango::SCALAR) {
          double vd = stod(value);
          Tango::DeviceAttribute da(attName,vd);
          self->write_attribute(da);
        } else {
          RAISE_EXCEPTION("Unexpected attribute type/format");
        }
        break;
      case Tango::DEV_BOOLEAN:
        if(att.get_data_format()==Tango::SCALAR) {
          Tango::DevBoolean vb = (stoi(value)!=0);
          Tango::DeviceAttribute da(attName,vb);
          self->write_attribute(da);
        } else {
          RAISE_EXCEPTION("Unexpected attribute type/format");
        }
        break;
      case Tango::DEV_LONG:
        if(att.get_data_format()==Tango::SCALAR) {
          Tango::DevLong vl = stol(value);
          Tango::DeviceAttribute da(attName,vl);
          self->write_attribute(da);
        } else {
          RAISE_EXCEPTION("Unexpected attribute type/format");
        }
        break;
      case Tango::DEV_SHORT:
        if(att.get_data_format()==Tango::SPECTRUM) {
          vector<string> fields;
          split(fields,value,',');
          vector<Tango::DevShort> vsa;
          for(int i=0;i<(int)fields.size();i++)
            vsa.push_back((Tango::DevShort)stol(fields[i]));
          Tango::DeviceAttribute da(attName,vsa);
          self->write_attribute(da);
        } else {
          RAISE_EXCEPTION("Unexpected attribute type/format");
        }
        break;
      default:
        RAISE_EXCEPTION("Unexpected attribute type/format");
    }

  }

  void SYMBFCleaning::save_attribute_property(string attName,string propName,double value) {

    Tango::DbDatum dbAtt(attName);
    Tango::DbDatum dbProp(propName);
    Tango::DbData dbData;

    dbAtt << 1; // One property
    dbProp << value;
    dbData.push_back(dbAtt);
    dbData.push_back(dbProp);
    get_db_device()->put_attribute_property(dbData);

  }

/*----- PROTECTED REGION END -----*/	//	SYMBFCleaning::namespace_ending
} //	namespace
